CHANGELOG.md, Tests/Recurly/Invoice_Test.php, Tests/Recurly/Subscription_Test.php, Tests/fixtures/invoices/create-201.xml, Tests/fixtures/invoices/preview-200.xml, Tests/fixtures/invoices/show-200.xml, Tests/fixtures/subscriptions/show-200.xml, lib/recurly/invoice.php, lib/recurly/subscription.php
Adding support for the custom invoice and subscription notes.
Approvers: @drewish
=> Read and Write custom invoice notes from API

lib/recurly/base.php, lib/recurly/subscription.php
Cleaning up some documentation
=> cleanup some documentation

CHANGELOG.md, README.md, lib/recurly/client.php
Get ready to kick out a 2.4.1.
=> Update versions for 2.4.1

CHANGELOG.md
I added a missing change log entry, also fixed some punctuation.
=> Missing changelog entry

CHANGELOG.md, lib/recurly/push_notification.php
Invoices notification are not usable because node is missing from the switch case.
=>   add invoice notification node

CHANGELOG.md, lib/recurly/client.php
@cbarton, Let's get it out there!
=> Bump version to 2.4.3

CHANGELOG.md, lib/recurly/client.php
=> bump to 2.4.5

.travis.yml
Simple tweak per http://docs.travis-ci.com/user/migrating-from-legacy/ to use their new builds. The timing should be pretty similar.
=> Use Travis' container-based builds

.gitignore, CHANGELOG.md, Tests/Recurly/Coupon_Redemption_Test.php, Tests/Recurly/Coupon_Test.php, Tests/Recurly/Subscription_Test.php, Tests/fixtures/accounts/redemption/show-200.xml, Tests/fixtures/coupons/show-200-2.xml, Tests/fixtures/coupons/show-200.xml, Tests/fixtures/coupons/show-redemptions-200.xml, Tests/fixtures/subscriptions/redemptions-200.xml, Tests/fixtures/subscriptions/show-200.xml, lib/recurly/account.php, lib/recurly/client.php, lib/recurly/coupon.php, lib/recurly/redemption.php, lib/recurly/subscription.php
Changes for Coupons 2.0
Approvers: @shulmang @drewish 
Please check over to see if anything was missed
=> Coupons 2 0 changes

CHANGELOG.md, lib/recurly/client.php
=> Bump to 2.4.6

lib/recurly/subscription_list.php
Remove 'non_renewing' state as it does not exist anymore.
Add 'canceled', 'expired', 'future', 'live' and 'past_due'.
=> Update subscription states

.travis.yml
Let's test against the new version of PHP.
=> Test on PHP 7

Tests/Recurly/Account_List_Test.php, Tests/Recurly/Invoice_List_Test.php, Tests/Recurly/Pager_Test.php, Tests/Recurly/Resource_Test.php, Tests/Recurly/Subscription_List_Test.php, Tests/Recurly/Transaction_List_Test.php, Tests/fixtures/invoices/index-200.xml, Tests/fixtures/notes/index-200.xml, Tests/fixtures/pager/head-200.xml, Tests/fixtures/pager/index-1-200.xml, Tests/fixtures/pager/index-2-200.xml, Tests/fixtures/pager/index-3-200.xml, Tests/fixtures/pager/show-200.xml, Tests/fixtures/subscriptions/index-200.xml, Tests/fixtures/transactions/index-200.xml, lib/recurly/account_list.php, lib/recurly/addon_list.php, lib/recurly/adjustment_list.php, lib/recurly/base.php, lib/recurly/coupon_list.php, lib/recurly/invoice_list.php, lib/recurly/pager.php, lib/recurly/plan_list.php, lib/recurly/redemption_list.php, lib/recurly/resource.php, lib/recurly/stub.php, lib/recurly/subscription_list.php, lib/recurly/transaction_list.php
Rework the pager to ensure it always has a href. This fixes the issue where pagers loaded from a stub only return the first page of records.
- Update the pagination section of the documentation to reflect these changes @bhelx
=> Rework Pager

CHANGELOG.md, lib/recurly/client.php
=> Bump 2.5.0

README.md
=> Update README to reflect new version

CHANGELOG.md, lib/recurly/client.php
* Added support for parsing `fraud` attribute on the `Transaction` class [#228](https://github.com/recurly/recurly-client-php/pull/228)
* Added support for setting`start_date` and `end_date` when creating an `Adjustment` (thanks to [imsagar](https://github.com/imsagar)) [#229](https://github.com/recurly/recurly-client-php/pull/229)
* Added support for Usage Based Billing [#227](https://github.com/recurly/recurly-client-php/pull/227)
=> Bump 2.5.2

CHANGELOG.md, Tests/Recurly/Transaction_Test.php, Tests/fixtures/transactions/show-200.xml
Fixes #216
Updates the fixture while I'm in here.
=> Add original_transaction to Recurly_Transaction

CHANGELOG.md, README.md, lib/recurly/client.php
Let's the get the changes for API V2.3 out the door!
=> Bump versions for 2.6.0 release

CHANGELOG.md, Tests/Recurly/Base_Test.php, lib/recurly/base.php
This is the same fix that @cyruscollier proposed in #255 but with different unit tests. It fixes #254.
=> Pass the client from pager to its items

CHANGELOG.md, Tests/Recurly/AccountAcquisition_Test.php, Tests/fixtures/account_acquisition/create-201.xml, Tests/fixtures/account_acquisition/destroy-204.xml, Tests/fixtures/account_acquisition/show-200.xml, lib/recurly.php, lib/recurly/account_acquisition.php, lib/recurly/base.php
Create:
```php
$account_code = 'pickles';
// Happy path
$acquisition = new Recurly_AccountAcquisition();
$acquisition->account_code = $account_code;
$acquisition->cost_in_cents = 1234;
$acquisition->currency = 'USD';
$acquisition->channel = 'paid_search';
$acquisition->subchannel = 'and dip';
$acquisition->campaign = 'asdf';
$acquisition->create();
// Sad path:
$acquisition = new Recurly_AccountAcquisition();
$acquisition->account_code = $account_code;
$acquisition->cost_in_cents = -20;
$acquisition->currency = 'USD';
$acquisition->channel = 'wrong';
$acquisition->subchannel = 'way to loooooooooooooooooooooooooooooooooooooooooooooooooooooooooooog';
$acquisition->campaign = 'super loooooooooooooooooooooooooooooooooooooooooooooooooooooooooooog';
$acquisition->create();
```
Fetch:
```php …
```
=> Account Acquisition data

CHANGELOG.md, lib/recurly.php
Addresses https://github.com/recurly/recurly-client-php/issues/271
=> Adding missing account balance require

Tests/Recurly/Coupon_Test.php, lib/recurly/coupon.php
Resolves https://github.com/recurly/recurly-client-php/issues/288
=> Writeable and updatable coupon description

CHANGELOG.md, Tests/Recurly/Subscription_Test.php, lib/recurly/client.php
Includes a test clean up and the fix from #326
=> Release 2.8.2

lib/recurly/addon.php
=> Add missing writeable fields to AddOn

Tests/Recurly/Invoice_Test.php, Tests/fixtures/invoices/show-200-updated-invoice.xml, lib/recurly/address.php, lib/recurly/invoice.php
Adds an `update()` method to the Invoice class so that changes can be made to an invoice via the API.
=> Allow client to edit an invoice

lib/recurly/client.php
Adds the OpenSSL version to the user agent.
=> Add OpenSSL version to User-Agent

README.md
https://github.com/recurly/recurly-client-php/issues/404#issuecomment-477234863
=> Remove out of date version from README

CHANGELOG.md, lib/recurly/client.php
* Add shipping address to Purchase [PR] (https://github.com/recurly/recurly-client-php/pull/435)
* Subscription timeframe changes [PR] (https://github.com/recurly/recurly-client-php/pull/419)
=> Release 2.12.8

README.md
This message is no longer relevant since v2 was released so long ago.
=> Cleanup old upgrade warning

lib/recurly.php, lib/recurly/client.php, lib/recurly/response.php, lib/recurly/util/http_validations.php
=> Moving statusCode checks

CHANGELOG.md, Tests/Recurly/Addon_Test.php, Tests/Recurly/Billing_Info_Test.php, Tests/fixtures/billing_info/show-sepa-200.xml, lib/recurly/addon.php, lib/recurly/billing_info.php, lib/recurly/client.php
- Tiered Pricing: Enable Add Ons to support 3 new pricing models (Tiered, Volume, and Stairstep)
- Add IBAN bank info as a part of billing info
- Add Mandate ID as part of billing info
=> Merge v2.26 features into v2 branch for release

lib/recurly/client.php, openapi/api.yaml
* Adds `deactivate_coupon` endpoint
=> Thu Mar 26 20:48:25 UTC 2020 Upgrade API version v2019-10-10

lib/recurly/resources/add_on.php, lib/recurly/resources/subscription_add_on.php, lib/recurly/resources/subscription_add_on_tier.php, lib/recurly/resources/tier.php, openapi/api.yaml
* Add `optional` to AddOnUpdate
* Adding quantity based pricing support
=> Tue Apr 14 20:57:43 UTC 2020 Upgrade API version v2019-10-10

lib/recurly/client.php, lib/recurly/resources/subscription_add_on.php, lib/recurly/resources/subscription_change_preview.php, openapi/api.yaml
- Adds `preview_subscription_change` operation.
- Adds `add_on_source` attribute/getter/setter to `SubscriptionAddOn`.
=> Wed Jul  1 02:11:57 UTC 2020 Upgrade API version v2019-10-10

.bumpversion.cfg, composer.json, lib/recurly/version.php
[Full Changelog](https://github.com/recurly/recurly-client-php/compare/3.3.0...HEAD)
- Wed Jul  1 02:11:57 UTC 2020 Upgrade API version v2019-10-10 [\#513](https://github.com/recurly/recurly-client-php/pull/513) ([douglasmiller](https://github.com/douglasmiller))
=> Release 3.4.0

openapi/api.yaml
- Updates openapi specification
=> Mon Jul  6 14:54:15 UTC 2020 Upgrade API version v2019-10-10

lib/recurly/client.php, lib/recurly/error_traits.php, lib/recurly/errors/timeout.php, lib/recurly/recurly_resource.php, lib/recurly/resources/add_on.php, lib/recurly/resources/add_on_mini.php, lib/recurly/resources/measured_unit.php, lib/recurly/resources/subscription_add_on.php, lib/recurly/resources/subscription_change.php, lib/recurly/resources/subscription_change_preview.php, lib/recurly/resources/usage.php, openapi/api.yaml
* Usage and measured units support
* Added `InvoiceCollection` to response for `CreateSubscriptionChange`
* Support `AddOnType` on addons
=> Latest Changes for 2019-10-10 (usage, measured units, etc)

lib/recurly/resources/subscription_change.php, lib/recurly/resources/subscription_change_preview.php, openapi/api.yaml
- Adds Custom Fields to the Subscription Change and Subscription Change Preview endpoints.
=> Mon Aug 31 19:51:28 UTC 2020 Upgrade API version v2019-10-10

lib/recurly/resources/coupon.php, lib/recurly/resources/export_dates.php, lib/recurly/resources/export_files.php, openapi/api.yaml
* Fixes issues with Automated Exports endpoints.
=> Latest Changes for 2019-10-10

.bumpversion.cfg, composer.json, lib/recurly/version.php
[Full Changelog](https://github.com/recurly/recurly-client-php/compare/3.7.0...HEAD)
- Latest Changes for 2019-10-10 [\#541](https://github.com/recurly/recurly-client-php/pull/541) ([douglasmiller](https://github.com/douglasmiller))
- Latest Changes for 2019-10-10 \(Automated Exports, additional resource data methods\) [\#537](https://github.com/recurly/recurly-client-php/pull/537) ([douglasmiller](https://github.com/douglasmiller))
**Fixed bugs:**
- Fixing casting for list types that are not in pagers [\#539](https://github.com/recurly/recurly-client-php/pull/539) ([douglasmiller](https://github.com/douglasmiller))
=> Release 3.8.0

lib/recurly/client.php, openapi/api.yaml
* Adds `restoreCoupon` operation.
=> Mon Oct 19 20:43:37 UTC 2020 Upgrade API version v2019-10-10

composer.json, lib/recurly/client.php, lib/recurly/errors/service_not_available.php, lib/recurly/resources/billing_info.php, lib/recurly/resources/coupon.php, lib/recurly/resources/invoice.php, lib/recurly/resources/subscription.php, openapi/api.yaml
* `Wallet` features:
* Adds operations for the `Wallet` feature of Recurly API:
* `createBillingInfo`
* `listBillingInfos`
* `getABillingInfo`
* `updateABillingInfo`
* `removeABillingInfo`
* Adds `getPrimaryPaymentMethod` method to the `BillingInfo` resource.
* Adds `getBillingInfoId` method to the `Invoice` and `Subscription` resources.
* `Item Coupons` features:
* Adds `getAppliesToAllItems` and `getItems` methods to the `Coupon` resource.
* Adds `ServiceNotAvailable` error class.
=> Latest Changes for 2019-10-10 (Wallet, Item Coupons)

.bumpversion.cfg, composer.json, lib/recurly/version.php
[Full Changelog](https://github.com/recurly/recurly-client-php/compare/3.9.0...HEAD)
- Latest Changes for 2019-10-10 \(Wallet, Item Coupons\) [\#564](https://github.com/recurly/recurly-client-php/pull/564) ([douglasmiller](https://github.com/douglasmiller))
- Implement Pager\#take [\#561](https://github.com/recurly/recurly-client-php/pull/561) ([joannasese](https://github.com/joannasese))
=> Release 3.10.0

README.md
Revised readme to call out Header case sensitivity
=> Update readme to include memo on headers

README.md
Revised readme to call out Header case sensitivity
=> Update readme to include headers memo

CHANGELOG.md, lib/recurly/client.php
- Bump PHP client library version to 2.12.19
- Update changelog
-----
* Implement Pager#take https://github.com/recurly/recurly-client-php/pull/562
* Augment and patch iban implementation https://github.com/recurly/recurly-client-php/pull/567
* Add `item_state` and `external_sku` to phpdocs https://github.com/recurly/recurly-client-php/pull/568
* Update readme to include headers memo https://github.com/recurly/recurly-client-php/pull/570
=> Release 2.12.19

lib/recurly/response.php
Update warning to match [sunset policy](https://developers.recurly.com/pages/api-v2/support-policy-and-roadmap.html).
=> Update language to match sunset policy

.bumpversion.cfg, composer.json, lib/recurly/version.php
[Full Changelog](https://github.com/recurly/recurly-client-php/compare/3.10.0...HEAD)
- Latest Changes for 2019-10-10 [\#577](https://github.com/recurly/recurly-client-php/pull/577) ([douglasmiller](https://github.com/douglasmiller))
- Latest Changes for 2019-10-10 [\#569](https://github.com/recurly/recurly-client-php/pull/569) ([douglasmiller](https://github.com/douglasmiller))
- Update readme to include memo on headers [\#571](https://github.com/recurly/recurly-client-php/pull/571) ([joannasese](https://github.com/joannasese))
=> Release 3.11.0

.bumpversion.cfg, composer.json, lib/recurly/version.php
[Full Changelog](https://github.com/recurly/recurly-client-php/compare/4.0.0...HEAD)
- Generated Latest Changes for v2021-02-25 [\#595](https://github.com/recurly/recurly-client-php/pull/595) ([recurly-integrations](https://github.com/recurly-integrations))
- Sync updates not ported from 3.x client [\#590](https://github.com/recurly/recurly-client-php/pull/590) ([douglasmiller](https://github.com/douglasmiller))
- Replace empty\(\) with is\_null\(\) [\#588](https://github.com/recurly/recurly-client-php/pull/588) ([joannasese](https://github.com/joannasese))
- Replace empty\(\) with is\_null\(\) [\#587](https://github.com/recurly/recurly-client-php/pull/587) ([joannasese](https://github.com/joannasese))
=> Release 4.0.1
