recurly/recurly-client-php

CHANGELOG.md
Tests/Recurly/Account_Test.php
Tests/fixtures/accounts/show-200.xml

This field will show up when the account is elligible and has been
location verified according to the VAT rules. It will be true when
passed and false when failed.
There weren't any needed changes for the library code here as it's a
read-only attribute. I just wanted to update the fixture and the test.

Adding vat_location_valid field to Account

---

CHANGELOG.md
Tests/Recurly/Invoice_Test.php
Tests/Recurly/Subscription_Test.php
Tests/fixtures/invoices/create-201.xml
Tests/fixtures/invoices/preview-200.xml
Tests/fixtures/invoices/show-200.xml
Tests/fixtures/subscriptions/show-200-changed-notes.xml
lib/recurly/invoice.php
lib/recurly/resource.php
lib/recurly/subscription.php

This adds the new `update_notes` path for `Subscription` and adds `vat_reverse_charge_notes` to `Invoice`. 
Relies on https://github.com/recurly/recurly-client-php/pull/115
Approvers: @drewish

Update notes path and vat_reverse_charge_notes

---

lib/recurly/invoice.php

added collection_method, net_terms, po_number
particularly adds support for creating invoices with manual
collection_method
resolves recurly/recurly-client-php#84

Adding missing fields to Invoice 

---

CHANGELOG.md
Tests/Recurly/Invoice_Test.php
Tests/fixtures/invoices/create-201.xml
Tests/fixtures/invoices/mark_failed-200.xml
Tests/fixtures/invoices/mark_successful-200.xml
Tests/fixtures/invoices/preview-200.xml
Tests/fixtures/invoices/show-with-prefix-200.xml
Tests/fixtures/subscriptions/preview-200-change.xml
lib/recurly/invoice.php

cc/ @drewish   
tests:
- Turn on the Country Invoice Sequencing feature with VAT taxes
- Create a VAT taxed invoice 
- `Recurly_Invoice::get('GB1000')->invoiceNumberWithPrefix()` should find the correct invoice and return its full invoice number.

Add Invoice#invoice_number_prefix and Invoice#invoiceNumberWithPrefix

---

CHANGELOG.md
lib/recurly/client.php

- Use # for PR numbers
- Fix typos
- Consistent formatting
Also bumps the version number.

Cleanup CHANGELOG for 2.4.0 release

---

composer.json

Looking at https://packagist.org/packages/recurly/recurly-client I noticed it's still calling the dev branch 2.3.x-dev  so let's bump that too.

Bump composer dev to 2.4.x

---

Tests/Recurly/Base_Test.php
lib/recurly/base.php

@bhelx noticed that we when you tried `$this->invoice->get()` in a `Recurly_Adjustment` the client wasn't passed through the `Recurly_Stub` to the `Recurly_Invoice` making it impossible to test the code. 
I wrote up a test to confirm that was the problem then located the issue. We were assigning the client to the object after its stubs had been created.

Ensure client is passed to stubs

---

CHANGELOG.md
Tests/Recurly/Adjustment_Test.php
Tests/Recurly/Invoice_Test.php
Tests/fixtures/invoices/refund-201.xml
lib/recurly/adjustment.php
lib/recurly/invoice.php
lib/recurly/resource.php

This pull request is to support both open amount and line item refunds on `Invoice`.
Approvers: @drewish 
Open Amount:
```php
$invoice = Recurly_Invoice::get('1002');  // get some invoice
$ref = $invoice->refundAmount(100);      // refund some amount in cents
var_dump($ref); // verify the returned refund invoice is correct
```
Line Item [WIP]:
```php
// get some invoice, preferably with multiple line items
$invoice = Recurly_Invoice::get('1002');
// grab out which ever ones you want to refund
$line_items = $invoice->line_items;
// You probably want to build new adjustment objects
// rather than modifying your existing line items
// and passing those in
$adjustment_map = function($line_item) {
return $line_item->toRefundAttributes();
};
$refunds = array_map($adjustment_map, $line_items); …
```

Support open amount and line item refunds

---

lib/recurly/response.php

Message updated based on https://docs.recurly.com/api/basics/rate-limits.

clarifies API rate limit exception

---

CHANGELOG.md
Tests/Recurly/Plan_Test.php
Tests/Recurly/Resource_Test.php
lib/recurly/resource.php

Fixes #148. This also syncs up the style for creating the `$attribute_node` in the `null` case.

Properly encode entities when serializing XML

---

README.md

Some clients are having trouble connecting to our API unless they specify a default timezone.

Docs timezone

---

CHANGELOG.md
Tests/Recurly/Billing_Info_Test.php
Tests/fixtures/billing_info/show-bank-account-200.xml
lib/recurly/billing_info.php

Adds ACH support for Billing Infos
cc/ @drewish  
tests:
```php
$billing_info->account_code = '<account-code>';
$billing_info->name_on_account = 'John Doe';
$billing_info->routing_number = '125200057';
$billing_info->account_number = '0123456789';
$billing_info->account_type = 'checking';
$billing_info->address1 = '123 Fake St';
$billing_info->city = 'San Francisco';
$billing_info->state ='CA';
$billing_info->country = 'US';
$billing_info->zip = '94107';
$billing_info->create();
```
- check the billing info to see that it reflects that info

Add bank account fields to billing info

---

CHANGELOG.md
lib/recurly/invoice.php

Missed a spot when adding the invoice number prefixes, we need to fetch the invoice PDF's using that prefix.
Fixes https://github.com/recurly/recurly-client-php/issues/143
cc/ @drewish 
tests:
- Create an invoice that has a VAT EU prefix
```php
$i = Recurly_Invoice::get('<invoice_number_with_prefix>');
file_put_contents('invoice.pdf', $i->getPdf());
```
- open up `invoice.pdf`, it should contain the invoice

Use invoice prefix when fetching PDF's

---

CHANGELOG.md
Tests/Recurly/Transaction_Test.php
Tests/fixtures/transactions/create-422.xml
Tests/fixtures/transactions/refund-202.xml
Tests/fixtures/transactions/show-200-error.xml
Tests/fixtures/transactions/show-200.xml

Adding `ip_address` to transactions now that it's exposed
https://docs.recurly.com/api/transactions#create-transaction
cc: @drewish 
Test:
`$transaction = Recurly_Transaction::get(‘<uuid>’);`
`print htmlspecialchars($transaction);`

Add ip_address to Transaction

---

CHANGELOG.md
lib/recurly/subscription.php

For back dating bank account authorization when importing subscriptions, the API user can specify a `bank_account_authorized_at` timestamp of when that authorization occurred.
cc/ @drewish  
tests:
```php
$account = Recurly_Account::get('<account_code>');
$sub = new Recurly_Subscription();
$sub->plan_code = '<plan_code>';
$sub->currency = 'USD';
$sub->account = $account;
$sub->bank_account_authorized_at = '2015-02-15T08:00:00+00:00';
$sub->create();
$sub = Recurly_Subscription::get($sub->uuid);
var_dump($sub->bank_account_authorized_at); //> 2015-02-15 08:00:00.000000"
```

Add bank_account_authorized_at to subscriptions

---

CHANGELOG.md
Tests/fixtures/transactions/create-422.xml
Tests/fixtures/transactions/show-200-error.xml
lib/recurly/transaction_error.php

Added `gateway_error_code` to `Transaction` now that it’s exposed https://docs.recurly.com/api/transactions/error-codes
cc: @whiteotter

Adding `gateway_error_code` to `Transaction`

---

Tests/Recurly/Transaction_Test.php

Adding specs that assert the transaction response messages and codes are accurate.
cc: @drewish 
To test out: `vendor/phpunit/phpunit/phpunit Tests/`

Spec for successfully submitted, declined transactions

---

CHANGELOG.md
lib/recurly/adjustment.php
lib/recurly/invoice.php

cc/ @drewish 
tests:
- Create a new invoice with 2 line items and make sure it is paid
- Attempt a transaction first line item refund:
```php
$inv = Recurly_Invoice::get('<invoice_number>');
$refInv = $inv->refund([$inv->line_items[0]->toRefundAttributes()], 'transaction');
print($refInv->invoice_number); // should contain the refund of the first line item
$refInv = $inv->line_items[1]->refund(null, false, 'transaction');
print($refInv->invoice_number); // should contain the refund of the last line item
```
- Create another invoice and make sure it is paid
- Attempt a transaction first open amount refund:
```php
$inv = Recurly_Invoice::get('<invoice_number>');
$refInv = $inv->refundAmount(1000, 'transaction');
print($refInv->invoice_number);
```

Add option to specify the refund_apply_order for invoice refunds

---

Tests/Recurly/Coupon_Redemption_Test.php
Tests/fixtures/accounts/redemption/destroy-204.xml
Tests/fixtures/accounts/redemption/show-200.xml
lib/recurly/redemption.php

While reviewing https://github.com/recurly/recurly-client-php/pull/164 I noticed that there were no tests for coupon redemptions.

Coupon Redemption tests

---

CHANGELOG.md
lib/recurly/transaction.php

cc/ @drewish 
tests:
- the following should create a tax exempt transaction:
```php
$transaction = new Recurly_Transaction();
$transaction->amount_in_cents = 1000; 
$transaction->currency = 'USD';
$transaction->tax_exempt = true;
$transaction->account = new Recurly_Account();
$transaction->account->account_code = '<account_code>';
$transaction->create();
print($transaction->uuid);
```

add tax_code, tax_exempt to transaction

---

CHANGELOG.md
Tests/fixtures/coupons/show-200-2.xml
Tests/fixtures/coupons/show-200-expired.xml
Tests/fixtures/coupons/show-200.xml
lib/recurly/coupon.php

**Description**:
Add support for new coupon duration attributes (duration, temporal_unit, temporal_amount)
**Additional approvers**:
@bhelx
**Testing**:
- Verify that new coupons can be created with duration=forever/single_use/temporal, single_use=true, & applies_for_months=n
- Verify that when reading all of the created coupons the values for duration, temporal_unit, temporal_amount, single_use, & applies_for_months are all correct
```
function new_coupon() {
$coupon = new Recurly_Coupon();
$coupon->coupon_code = uniqid();
$coupon->name = uniqid();
$coupon->discount_in_cents->addCurrency('USD',200);
return $coupon;
}
$coupon = new_coupon();
$coupon->duration = 'forever';
$coupon->create();
$coupon = Recurly_Coupon::get($coupon->coupon_code);
print($coupon->duration); …
```

adding support for new coupon duration attributes

---

README.md
lib/recurly/client.php
lib/recurly/response.php

Updating all links that referenced the old docs url.
Before: https://docs.recurly.com/api
After: https://dev.recurly.com
cc: @bhelx

Updating docs links

---

CHANGELOG.md
Tests/Recurly/Plan_Test.php
Tests/fixtures/plans/show-200.xml
lib/recurly/plan.php

Exposing a `setup_fee_accounting` code to the client library since it's now available.

Adding setup_fee_accounting_code

---

CHANGELOG.md
README.md
lib/recurly/client.php

This is meant to address https://github.com/recurly/recurly-client-php/issues/173
@drewish and I have discussed and changed this to accept a path rather than a bundle. I'm going to monitor how well this solves the problem and only reconsider the bundle if enough people need it.
@csmb and I will verify that this work in his bad php installation.
Approvers: @csmb @drewish

Add option for setting CA cert path

---

lib/recurly/account.php

This fixes issue https://github.com/recurly/recurly-client-php/issues/187 reported by @matylla.
Need @shulmang to confirm the intent as he is the original author.
The code below will throw the error described by @matylla when referencing `$account->redemption`. The fix should correctly build the stub and calling `get()` on the stub should correctly fetch the redemption.
```php
// choose an account with a redemption
$account = Recurly_Account::get('myaccountcode');
print $account->redemption;
print $account->redemption->get();
```

Fix Account redemption stub

---

CHANGELOG.md
lib/recurly/account.php
lib/recurly/addon.php
lib/recurly/adjustment.php
lib/recurly/billing_info.php
lib/recurly/coupon.php
lib/recurly/invoice.php
lib/recurly/plan.php
lib/recurly/redemption.php
lib/recurly/subscription.php
lib/recurly/transaction.php

This addressed issue https://github.com/recurly/recurly-client-php/issues/177
These attributes appear to be vestigial

Remove unused nestedAttributes

---

CHANGELOG.md
Tests/Recurly/Coupon_Test.php
Tests/fixtures/coupons/update-201.xml
lib/recurly/coupon.php
lib/recurly/resource.php

Adding support for editing and restoring coupons.
* With an active coupon
```php
$coupon = Recurly_Coupon::get('ahhahshs');
$coupon->name = 'new name';
$coupon->max_redemptions = 99;
$coupon->max_redemptions_per_account = 3;
$coupon->redeem_by_date = '2025-09-09';
$coupon->description = 'derp description';
$coupon->invoice_description = 'derp description';
$coupon->update();
print $coupon->name . "\n";
print $coupon->max_redemptions . "\n";
print $coupon->max_redemptions_per_account . "\n";
print $coupon->description . "\n";
print $coupon->invoice_description . "\n";
```
* Do the same thing with an expired coupon but use `$coupon->restore()` instead of `$coupon->update()`

Support editing and restoring coupons

---

Tests/Recurly/Coupon_Test.php
Tests/fixtures/unique_coupons/generate-201.xml
Tests/fixtures/unique_coupons/index-200.xml
lib/recurly.php
lib/recurly/base.php
lib/recurly/client.php
lib/recurly/coupon.php
lib/recurly/unique_coupon_code_list.php

Adds support for creating bulk coupons and also generating coupon codes.
* Generate a bulk coupon and make sure there is room to generate some additional test codes
* This should generate 10 codes and return an array of the 10 coupons
```php
$coupon = Recurly_Coupon::get('mybulkcoupon');
$coupon_list = $coupon->generate(10);
foreach ($coupon_list as $coupon) {
print $coupon->coupon_code . "\n";
}
```
* This code should iterate through all the unique codes assigned to the parent bulk code.
```php
$coupon = Recurly_Coupon::get('mybulkcoupon');
$codes = $coupon->unique_coupon_codes->get();
foreach ($codes as $coup) {
print $coup->coupon_code . "\n";
}
```

Support bulk coupons and generate codes

---

CHANGELOG.md
Tests/Recurly/Account_Test.php
Tests/fixtures/accounts/create-201.xml
Tests/fixtures/accounts/show-200.xml
lib/recurly/account.php

Adding support for writing the `cc_emails` attribute on the `Account` class
```php
$account = Recurly_Account::get('benjamin');
$account->cc_emails = 'test3@example.com,test4@example.com';
$account->update();
// Refetch the account
$account = Recurly_Account::get('benjamin');
print $account->cc_emails;
```

Add support for cc_emails on Account

---

CHANGELOG.md
lib/recurly/redemption.php

I believe this may be related to Issue https://github.com/recurly/recurly-client-php/issues/196
The delete_url was looking like this:
`/v2/accounts/<accountcode>/redemptions/33ee88ee7d4124a7f9ca9c488d8d4018s/33ee88ee7d4124a7f9ca9c488d8d4018`
b/c it expected the resource location to still be the singular like so: `/v2/accounts/<accountcode>/redemption`
Using this code to test:
```php
try {
$account = Recurly_Account::get('test8');
$r = $account->redemption->get();
$r->delete($account->account_code);
} catch (Recurly_NotFoundError $e) {
print "Account not found: $e";
}
```

Redemptions now point to the correct url

---

CHANGELOG.md
lib/recurly/billing_info.php

This allows the merchant to send a custom currency on billing info creation and update for verification purposes. For instance, if your site default is USD and you are trying to verify for EUR, you may end up having two verifications.
You only need to set the `currency` attribute on the billing info object. You can do this on create or update. Also works if you are using a token instead of the card info.
```php
try {
$billing_info->account_code = 'other_account';
$billing_info->first_name = 'Verena';
$billing_info->last_name = 'Example';
$billing_info->number = '4111-1111-1111-1111';
$billing_info->verification_value = '123';
$billing_info->month = 11;
$billing_info->year = 2019;
$billing_info->currency = 'EUR';
$billing_info->create();
print …
```

Adding currency attribute to BillingInfo

---

CHANGELOG.md
lib/recurly/client.php

* Added support for `cc_emails` attribute on the `Account` class [#202](https://github.com/recurly/recurly-client-php/pull/202)
* Fix bug with incorrect `delete_uri` on the `Redemption` class [#201](https://github.com/recurly/recurly-client-php/pull/201)
* Added `currency` attribute to `BillingInfo` [#205](https://github.com/recurly/recurly-client-php/pull/205)

Bump 2.5.1

---

README.md

I think it would be helpful for users of this library to know they should utilize an OpenSSL version to one that is using TLS v1.1+ since Recurly will slowly be deprecating any protocols that do not use TLS v1.1.

Add a note about supporting TLS in the README.md

---

CHANGELOG.md
Tests/Recurly/Transaction_Test.php
Tests/fixtures/transactions/show-200.xml
lib/recurly.php
lib/recurly/base.php
lib/recurly/currency.php
lib/recurly/fraud_info.php

If it's available, the transaction may contain a fraud object with some fraud information.
Ruby PR: recurly/recurly-client-ruby#244

Parse Fraud object when available

---

Tests/fixtures/notes/index-200.xml
lib/recurly/note_list.php
lib/recurly/pager.php

Notes weren't loaded after rewind() was called. The name didn't match what
was in the XML so __parseXmlToObject() was never called and hence the object
were never added to $this->_objects.
While I'm here I fixed a bug in the pager where it'd keep checking for a
next link so it could reload... that wasn't ever going to happen so it's
better to give a hard error.
Test this by trying to run the [notes sample code in our docs](https://dev.recurly.com/docs/list-account-notes):
```php
try {
$notes = Recurly_NoteList::get('b6f5783');
foreach ($notes as $note) {
print "Note: {$note->message}\n";
}
} catch (Recurly_NotFoundError $e) {
print "Invalid account code: $e";
}
```

Return correct node name for Recurly_NoteList

---

lib/recurly/coupon.php

Description: Adds attributes for free trial coupons.
Testing the change:
create a free trial coupon by creating a coupon with the following attributes and using "free_trial" for the discount type
```
$coupon->discount_type = 'free_trial';
$coupon->free_trial_amount = 5;
$coupon->free_trial_unit = "month";
```
once the coupon is created, get, update, and delete the coupon

updates Recurly_Coupon for free trial coupons

---

lib/recurly/client.php

Let's clean out some old, unused paths related to the deprecated transparent post API.

Drop old transparent post paths

---

Tests/Recurly/Pager_Test.php
lib/recurly/addon.php
lib/recurly/address.php
lib/recurly/adjustment.php
lib/recurly/billing_info.php
lib/recurly/coupon.php
lib/recurly/invoice.php
lib/recurly/measured_unit.php
lib/recurly/note.php
lib/recurly/plan.php
lib/recurly/resource.php
lib/recurly/subscription.php
lib/recurly/subscription_addon.php
lib/recurly/tax_detail.php
lib/recurly/transaction.php
lib/recurly/usage.php

Follow up to https://github.com/recurly/recurly-client-php/pull/227/files#r65484206
Let's cut down on some of the boilerplate code in every class by providing a default implementation. We could probably just remove the function entirely but I'll leave that for another PR.

Provide default getWriteableAttributes()

---

README.md
Tests/Recurly/Account_List_Test.php
Tests/Recurly/Account_Test.php
Tests/Recurly/Addon_Test.php
Tests/Recurly/Adjustment_Test.php
Tests/Recurly/Base_Test.php
Tests/Recurly/Billing_Info_Test.php
Tests/Recurly/Client_Test.php
Tests/Recurly/Coupon_Redemption_Test.php
Tests/Recurly/Coupon_Test.php
Tests/Recurly/Currency_List_Test.php
Tests/Recurly/Invoice_List_Test.php
Tests/Recurly/Invoice_Test.php
Tests/Recurly/MeasuredUnit_List_Test.php
Tests/Recurly/MeasuredUnit_Test.php
Tests/Recurly/Note_List_Test.php
Tests/Recurly/Pager_Test.php
Tests/Recurly/Plan_Test.php
Tests/Recurly/Resource_Test.php
Tests/Recurly/Subscription_List_Test.php
Tests/Recurly/Subscription_Test.php
Tests/Recurly/Transaction_List_Test.php
Tests/Recurly/Transaction_Test.php
Tests/Recurly/Usage_Test.php
Tests/bootstrap.php
phpunit.xml.dist

Standard practice, when I move in to work on a project that I can see uses PHPUnit from the `composer install` output, I expect to be able to run `vendor/bin/phpunit` from the root of the project and the default test suite to be executed. Given I was creating the PHPUnit configuration, I leveraged it to avoid having to manually require the support code.

Use PHPUnit configuration file

---

Tests/Recurly/Subscription_Test.php
lib/recurly/subscription_addon.php

Addresses https://github.com/recurly/recurly-client-php/issues/240
Reported By: @ScottSpittle 
We are seeing an issue with updating subscriptions containing add ons. Using the `updateImmediately` method was generating some xml which was trying to update immutable fields for the subscription add ons on the backend. The update payload was looking something like this:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<subscription>
<quantity>2</quantity>
<timeframe>now</timeframe>
<subscription_add_ons>
<subscription_add_on>
<add_on_code>marketing_emails</add_on_code>
<add_on_type>fixed</add_on_type>
<quantity>1</quantity>
<unit_amount_in_cents>5</unit_amount_in_cents>
</subscription_add_on>
</subscription_add_ons>
</subscription>
```
And the resulting error:
```xml
<?xml version="1.0" …
```

Fix subscription updates when subcription has add_ons

---

lib/recurly/account.php

> Notice: Only variable references should be returned by reference

Assign to a variable to allow returning a reference

---

lib/recurly/redemption_list.php
lib/recurly/unique_coupon_code_list.php

The coupon listings all require a parent object. Both of these functions that are being removed generate calls to invalid paths and result in 404s:
```php
Recurly_CouponRedemptionList::get()->count();
Recurly_UniqueCouponCodeList::get()->count();
```
In comparison these will return data:
```php
$accountCode = Recurly_AccountList::get()->current()->account_code;
$invoiceNumber = Recurly_InvoiceList::get()->current()->invoice_number;
$subscriptionUuid = Recurly_SubscriptionList::get()->current()->uuid;
Recurly_CouponRedemptionList::getForAccount($accountCode, $options)->count();
Recurly_CouponRedemptionList::getForInvoice($invoiceNumber, $options)->count();
Recurly_CouponRedemptionList::getForSubscription($subscriptionUuid, $options)->count(); …
```

Coupon lists require a parent object

---

CHANGELOG.md
Tests/Recurly/Client_Test.php
Tests/fixtures/client/deprecated-200.xml
lib/recurly/response.php

This will start printing warning messages when a deprecated API version is detected. Ideally we'd be doing something like `trigger_error($message, E_USER_DEPRECATED)` but I'm worried people might not have `error_reporting()` set to a compatible level to avoid it being treated as a fatal error.

Warn on API deprecation

---

Tests/fixtures/accounts/create-201.xml
Tests/fixtures/accounts/index-200.xml
Tests/fixtures/accounts/show-200.xml
Tests/fixtures/accounts/update-200.xml

**Description**: Adding support to the `closed_at` tag
**Testing**:
- Close an account
- Reference the account and make sure you can reference the `closed_at` object property:
```
print_r( $account->closed_at );
[closed_at] => DateTime Object
(
[date] => 2015-07-07 18:49:06
[timezone_type] => 2
[timezone] => Z
)
```

Adding closed_at account tag to fixtures

---

CHANGELOG.md
Tests/Recurly/Note_List_Test.php
Tests/Recurly/Pager_Test.php
lib/recurly/addon_list.php
lib/recurly/note_list.php
lib/recurly/pager.php

Here's the testing code I was using to check this out
```php
function fetchIt($list) {
$initialCount = $list->count();
print "\thas {$initialCount} rows\n";
// print "links:\n"; var_dump($list->getLinks());
// print "href:\n"; var_dump($list->getHref());
$first = $list->current()->getHref();
print "\tfirst is {$first}\n";
$count = 0;
foreach ($list as $item) {
++$count;
}
assert($initialCount == $count);
$list->rewind();
print "\tfirst is {$list->current()->getHref()}\n\n";
assert($first == $list->current()->getHref());
}
$accountCode = 'd4a354bb326f3b7386ad351d7c0750';
$planCode = 'perferendis_in8';
$options = array('per_page' => 200, 'sort' => 'updated_at', 'order' => 'asc', 'begin_time' => '2016-01-01');
fetchIt(Recurly_AccountList::get($options)); …
```

Add support for new pagination

---

CHANGELOG.md
lib/recurly/addon.php
lib/recurly/adjustment.php
lib/recurly/plan.php
lib/recurly/subscription.php
lib/recurly/subscription_addon.php

```php
// Set the schedule types on a plan
$plan = Recurly_Plan::get('gold');
$plan->revenue_schedule_type = 'at_range_end';
$plan->setup_fee_revenue_schedule_type = 'at_range_start';
$plan->update();
```
```php
// Set the schedule type on an add-on
$add_on = Recurly_Addon::get('gold', 'ipaddresses');
$add_on->revenue_schedule_type = 'never';
$add_on->update();
```
```php
// Set the schedule type on a new adjustment
$charge = new Recurly_Adjustment();
$charge->account_code = '1';
$charge->description = 'Charge for extra bandwidth';
$charge->unit_amount_in_cents = 5000;
$charge->currency = 'USD';
$charge->revenue_schedule_type = 'at_range_start';
$charge->create();
```
```php
// Set the schedule on an subscription and add-on
$subscription = new Recurly_Subscription(); …
```

Add revenue_schedule_type support

---

CHANGELOG.md
Tests/Recurly/Adjustment_Test.php
lib/recurly/adjustment.php

Adjustment objects will soon be allowed to specify the custom origin of `external_gift_card` for credits on an account originating from an external (3rd party) gift card provider. This allows merchants to accept gift cards and collect funds from them outside of Recurly, but enter credits for those gift cards into Recurly to be used to pay for subscriptions. This origin will not work for charges, only credits.
Existing clients will see no change in their integration as an origin will be chosen for their adjustments automatically as it has been done in the past.
This feature is not currently GA and will need to be enabled by contacting sales/support.

Allow adjustments to specify an origin

---

lib/recurly/account.php
lib/recurly/addon.php
lib/recurly/address.php
lib/recurly/adjustment.php
lib/recurly/billing_info.php
lib/recurly/coupon.php
lib/recurly/invoice.php
lib/recurly/measured_unit.php
lib/recurly/plan.php
lib/recurly/redemption.php
lib/recurly/subscription.php
lib/recurly/subscription_addon.php
lib/recurly/transaction.php
lib/recurly/usage.php

Right now we've got a lot of overhead setting up static `$_writeableAttributes` and `$_requiredAttributes` variable that are only used by accessor functions. We can remove a lot of boilerplate code by just having the accessors return the arrays directly.

Simplify writable attributes

---

lib/recurly/gift_card.php
lib/recurly/subscription.php

`preview()` indirectly calls `__parseXmlToObject()` which resets the `_unsavedKeys` property. So when `save()` is called it appears there is nothing to do. There's not an easy fix for this so I think we can just document the behavior.

Document that you can't call preview() then save()

---

CHANGELOG.md
Tests/Recurly/Account_Test.php
Tests/Recurly/Subscription_Test.php
Tests/fixtures/accounts/create-201.xml
lib/recurly.php
lib/recurly/account.php
lib/recurly/base.php
lib/recurly/resource.php
lib/recurly/shipping_address.php
lib/recurly/shipping_address_list.php
lib/recurly/subscription.php

Adding shipping address support. Allows adding and removing multiple shipping addresses to/from an account. You can also add/remove a shipping address on a subscription.
```php
// work shipping address
$shad1 = new Recurly_ShippingAddress();
$shad1->nickname = "Work";
$shad1->first_name = "Verena";
$shad1->last_name = "Example";
$shad1->company = "Recurly Inc.";
$shad1->phone = "555-555-5555";
$shad1->email = "verena@example.com";
$shad1->address1 = "123 Main St.";
$shad1->city = "San Francisco";
$shad1->state = "CA";
$shad1->zip = "94110";
$shad1->country = "US";
// home shipping address
$shad2 = new Recurly_ShippingAddress();
$shad2->nickname = "Home";
$shad2->first_name = "Verena";
$shad2->last_name = "Example";
$shad2->phone = "555-555-5555";
$shad2->email = "verena@example.com"; …
```

Shipping Address Support

---

CHANGELOG.md
Tests/Recurly/Recurly_Stub_Test.php
lib/recurly/stub.php

Please test this improvements. I think this will be helpful.

Added filters support for stub

---

CHANGELOG.md
Tests/Recurly/Billing_Info_Test.php
Tests/fixtures/billing_info/show-200.xml
lib/recurly/billing_info.php

Description: Adds company attribute to billing_info
Testing the change:
create billing info on an account and include a company name in the billing info
```php
$billing_info->company = 'Company Name'
```

adds company to writeable billing_info attributes

---

lib/recurly/addon.php

Fix for a small bug where the addon class does not return the writeable attributes, resulting in $addon->create() to fail.

Fixed addon creation bug.

---

lib/recurly/errors.php
lib/recurly/response.php

Adding ability to get Recurly error code from Recurly_Error Exception

---

Tests/Recurly/ShippingAddress_Test.php
Tests/fixtures/shipping_addresses/create-201.xml
Tests/fixtures/shipping_addresses/index-200.xml
Tests/fixtures/shipping_addresses/update-200.xml
lib/recurly/account.php
lib/recurly/shipping_address.php

It seems we weren't able to create shipping addresses on existing accounts before. This method allows that. Also added the `update()` method.
```php
// work shipping address
$shad1 = new Recurly_ShippingAddress();
$shad1->nickname = "Work";
$shad1->first_name = "Verena";
$shad1->last_name = "Example";
$shad1->company = "Recurly Inc.";
$shad1->phone = "555-555-5555";
$shad1->email = "verena@example.com";
$shad1->address1 = "123 Main St.";
$shad1->city = "San Francisco";
$shad1->state = "CA";
$shad1->zip = "94110";
$shad1->country = "US";
// home shipping address
$shad2 = new Recurly_ShippingAddress();
$shad2->nickname = "Home";
$shad2->first_name = "Verena";
$shad2->last_name = "Example";
$shad2->phone = "555-555-5555";
$shad2->email = "verena@example.com";
$shad2->address1 = "123 Dolores …
```

Create shipping addresses on existing accounts and allow updates

---

CHANGELOG.md
lib/recurly/client.php

* Added property documentation to several classes (thanks to [phpdave](https://github.com/phpdave)) [#278](https://github.com/recurly/recurly-client-php/pull/278)
* Added company attribute to billing info [#280](https://github.com/recurly/recurly-client-php/pull/280)
* Fixed add-on creation bug [#286](https://github.com/recurly/recurly-client-php/pull/286)
* Create shipping addresses on existing accounts and allow updates [#289](https://github.com/recurly/recurly-client-php/pull/289)
* Adding ability to get Recurly error code from Recurly_Error Exception [#291](https://github.com/recurly/recurly-client-php/pull/291)

Bump 2.7.1

---

Tests/Recurly/Adjustment_Test.php
Tests/Recurly/Billing_Info_Test.php
Tests/Recurly/Transaction_Test.php
Tests/fixtures/billing_info/show-200.xml
lib/recurly/base.php

Resolves #210
Resolves #245
This adds a method `getType` on every resource object which returns the xml attribute `type`. This can currently be found on Adjustments, Transactions, and BillingInfos.

Adds a getType method to all Resources

---

Tests/Recurly/Pager_Test.php
lib/recurly/pager.php

The count() class method should be called when using count($subscriptionList).

The Pager should implement the Countable interface

---

lib/recurly/response.php

Resolves #284 
Resolves #281 
Some coupon validation errors are shaped like normal field errors, for instance:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<error>
<symbol>subscription_must_change</symbol>
<description>You must change the subscription in order to redeem a coupon.</description>
</error>
```
instead of what would be expected:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<errors>
<error field="subscription.coupon_code" symbol="subscription_must_change">You must change the subscription in order to redeem a coupon.</error>
</error>
```
Example code:
```php
$active_subscription = '3b1c9a5c19f46a8e205abe409ebe3c01';
try {
$subscription = Recurly_Subscription::get($active_subscription);
$subscription->coupon_code = 'j32yaysm6g';
$subscription->quantity = 2; …
```

Parse incorrectly shaped validation errors

---

Tests/Recurly/Invoice_Test.php
Tests/Recurly/Transaction_Test.php
Tests/fixtures/transactions/create-200.xml
lib/recurly/invoice.php
lib/recurly/transaction.php

Resolves #141 
Adds the ability to ["Enter an offline payment for a manual invoice"](https://dev.recurly.com/docs/enter-an-offline-payment-for-a-manual-invoice-beta). If this is merged, then the code example on that page will have to be updated. This picks up on the work of @cgerrior in PR #154

Adds external paymnets to invoices

---

lib/recurly/delivery.php
lib/recurly/gift_card.php

Looks like we added another `delivery` field when we meant to add `deliver_at`
\cc @elliottbernstein

GiftCard: deliver_at goes on the Delivery object

---

CHANGELOG.md
lib/recurly/client.php

* Require export files [#296](https://github.com/recurly/recurly-client-php/pull/296)
* Writeable and updatable coupon description [#297](https://github.com/recurly/recurly-client-php/pull/297)
* Adds a `getType` method to all Resources [#299](https://github.com/recurly/recurly-client-php/pull/299)
* The Pager should implement the Countable interface (thanks to [naderman]()) [#282](https://github.com/recurly/recurly-client-php/pull/282)
* Parse incorrectly shaped validation errors [#298](https://github.com/recurly/recurly-client-php/pull/298)
* Adds external payments to invoices [#309](https://github.com/recurly/recurly-client-php/pull/309)
* GiftCard: `deliver_at` goes on the Delivery object [#307](https://github.com/recurly/recurly-client-php/pull/307)
* Changes for API v2.5 …

Bump 2.7.2

---

Tests/Recurly/Plan_Test.php
Tests/Recurly/Subscription_Test.php
Tests/fixtures/plans/show-200.xml
Tests/fixtures/subscriptions/show-200.xml
lib/recurly/plan.php

This adds the new read/write boolean field to plan `trial_requires_billing_info` and a new read only string field to subscription: `no_billing_info_reason`

Add trial requires billing info field and no billing info reason field

---

Tests/Recurly/Purchase_Test.php
Tests/Recurly/ShippingAddress_Test.php
Tests/fixtures/purchases/create-201.xml
Tests/fixtures/purchases/create-422.xml
Tests/fixtures/purchases/preview-200.xml
lib/recurly.php
lib/recurly/address.php
lib/recurly/adjustment.php
lib/recurly/purchase.php

Purchases endpoint.
```php
$purchase = new Recurly_Purchase();
$purchase->currency = 'USD';
$purchase->collection_method = 'automatic';
$purchase->account = new Recurly_Account();
$purchase->account->account_code = 'aba9209a-aa61-4790-8e61-0a2692435fee';
$purchase->account->address->phone = "555-555-5555";
$purchase->account->address->email = "verena@example.com";
$purchase->account->address->address1 = "123 Main St.";
$purchase->account->address->city = "San Francisco";
$purchase->account->address->state = "CA";
$purchase->account->address->zip = "94110";
$purchase->account->address->country = "US";
$billing_info->number = '4111-1111-1111-1111';
$billing_info->month = 12;
$billing_info->year = 2019;
$billing_info->verification_value = '123'; …
```

Purchases endpoint

---

.travis.yml
README.md
composer.json

HHVM is no longer supported on Ubuntu Precise. This is needed to get the tests to run again.

Remove 5.3 Support and upgrade Travis to support HHVM

---

Tests/Recurly/Account_List_Test.php
Tests/Recurly/Client_Test.php
Tests/Recurly/Coupon_Test.php
Tests/Recurly/GiftCard_List_Test.php
Tests/Recurly/MeasuredUnit_List_Test.php
Tests/Recurly/Note_List_Test.php
Tests/Recurly/Pager_Test.php
Tests/Recurly/Subscription_Test.php
Tests/fixtures/accounts/index-200.xml
Tests/fixtures/export_dates/index-200.xml
Tests/fixtures/export_files/index-200.xml
Tests/fixtures/gift_cards/index-200.xml
Tests/fixtures/invoices/index-200.xml
Tests/fixtures/measured_units/index-200.xml
Tests/fixtures/notes/index-200.xml
Tests/fixtures/pager/head-200.xml
Tests/fixtures/pager/index-1-200.xml
Tests/fixtures/pager/index-2-200.xml
Tests/fixtures/pager/index-3-200.xml
Tests/fixtures/subscriptions/index-200.xml
Tests/fixtures/transactions/index-200.xml
Tests/fixtures/unique_coupons/generate-201.xml
Tests/fixtures/unique_coupons/index-200.xml
lib/recurly/base.php
lib/recurly/client.php
lib/recurly/pager.php

This is for API v2.6.
The X-Records header was removed on all GET index endpoints. You must
now call HEAD explicitly to get the header and thus the count.
For instance, say you want to get the count of all Accounts in your site:
```php
$accounts = Recurly_AccountList::get();
print $accounts->count() . "\n"; // 1033
```
This only works when the internal `_objects` array is empty. Calling `->current()` or any other method that loads the page into memory will change the behavior of this method to return the count of the page:
```php
$accounts = Recurly_AccountList::get();
print $accounts->count() . "\n"; // 1033
$accounts->current();
print $accounts->count() . "\n"; // 50
```

Remove X-Records header

---

CHANGELOG.md

Looks like we were missing this changelog update.

Update CHANGELOG with 2.8.0 release

---

lib/recurly/adjustment.php
lib/recurly/client.php
lib/recurly/purchase.php
lib/recurly/resource.php
lib/recurly/shipping_address.php
lib/recurly/subscription.php

API v2.7 only has 1 feature, the updates to the purchases endpoint.
```php
$purchase = new Recurly_Purchase();
$purchase->currency = 'USD';
$purchase->collection_method = 'automatic';
$purchase->account = new Recurly_Account();
$purchase->account->account_code = 'aba9209a-aa61-4790-8e61-0a2692435fee';
$purchase->account->first_name = "Benjamin";
$purchase->account->last_name = "Du Monde";
$purchase->account->address->phone = "555-555-5555";
$purchase->account->address->email = "verena@example.com";
$purchase->account->address->address1 = "123 Main St.";
$purchase->account->address->city = "San Francisco";
$purchase->account->address->state = "CA";
$purchase->account->address->zip = "94110";
$purchase->account->address->country = "US"; …
```

API version 2.7

---

CHANGELOG.md
README.md
lib/recurly/client.php

This bumps us to API v2.7 but does not contain any breaking changes.
* Bump API v2.7 (purchase endpoint updates) [#319](https://github.com/recurly/recurly-client-php/pull/319)
* Enhancement: Enable IntelliSense (IDE friendly) for class properties (Part 2) Invoice and Subscription (thanks to @phpdave) [#279](https://github.com/recurly/recurly-client-php/pull/279)

Bump 2.8.1

---

Tests/Recurly/Subscription_Test.php
Tests/bootstrap.php
lib/recurly/subscription.php

it is my first contribution to this repo, but it looks like creating a test in one commit (for the use case i raised bug #325 for) and fix it the follow up commit seems suitable.
all tests pass for me
please let me know whether i need to or can improve this contribution in any way to get this PR accepted
thanks!

Add nested flag

---

Tests/Recurly/Subscription_Test.php
lib/recurly/subscription.php

This is an API v2.8 change and is thus going into the `api_version_2_8` branch.
This allows the merchant to tag a subscription being imported as a trial to ensure Recurly's trial conversion report does not include it as a true trial and instead as an active subscription.

Add writeable imported_trial bool to subscription

---

Tests/Recurly/Purchase_Test.php
lib/recurly/purchase.php

This is going into the API v2.8 branch. Adds 3 custom invoice notes to the `Purchase` resource.

Custom Invoice notes on Purchase

---

CHANGELOG.md
Tests/Recurly/Purchase_Test.php
Tests/Recurly/Subscription_Test.php
lib/recurly/client.php
lib/recurly/purchase.php
lib/recurly/subscription.php

This release will upgrade us to API version 2.8.
- Added custom invoice notes to `Purchase` [#332](https://github.com/recurly/recurly-client-php/pull/332)
- Added `imported_trial` boolean field to `Subscription` [#331](https://github.com/recurly/recurly-client-php/pull/331)
There is one breaking changes in this API version you must consider. All `country` fields must now
contain valid [2 letter ISO 3166 country codes](https://www.iso.org/iso-3166-country-codes.html). If your country code fails validation, you will receive a validation error. This affects any endpoint where an address is collected.

Bump 2.9.0, API version 2.8

---

lib/recurly/invoice.php
lib/recurly/transaction.php

This adds the documentation for the `subscriptions` links on the `Invoice` and `Transaction`. This was missed in the 2.8 release. Code is not required because links are dynamically created from xml.

Adds documentation for subscriptions links

---

Tests/Recurly/AccountBalance_Test.php
Tests/Recurly/Addon_Test.php
Tests/Recurly/Plan_Test.php
lib/recurly/account_balance.php
lib/recurly/addon.php
lib/recurly/plan.php

Three sub-classes of `Recurly_Resource` (`Recurly_Plan`, `Recurly_Addon`, and `Recurly_AccountBalance`) use overload their parents' `__construct()` methods, but do not accept arguments. This makes it impossible to use mocked `Recurly_Client` objects during testing when working with these three resources, meaning tests can't run without actually calling the Recurly API.
This PR ensures that these resources can accept `$href` and `$client` arguments, passing them through to the parent constructor.

Ensure compatibility between Recurly_Resource constructors

---

Tests/Recurly/Billing_Info_Test.php
Tests/Recurly/Purchase_Test.php
Tests/fixtures/purchases/authorize-200.xml
lib/recurly/billing_info.php
lib/recurly/client.php
lib/recurly/purchase.php

This PR contains the changes needed to bump to API version 2.9.
1. Adding the `authorize` endpoint for Purchases. You can read about authorize in [the dev docs](https://dev.recurly.com/docs/authorize-purchase). Example:
```php
$purchase = new Recurly_Purchase();
$purchase->currency = 'USD';
$purchase->collection_method = 'automatic';
$purchase->account = new Recurly_Account();
// In this case, email is required
$purchase->account->email = 'benjamin.dumonde@example.com';
$purchase->account->account_code = 'aa61-4790-8e61-0a2692435fee';
$purchase->account->first_name = "Benjamin";
$purchase->account->last_name = "Du Monde";
$purchase->account->address->phone = "555-555-5555";
$purchase->account->address->email = "verena@example.com";
$purchase->account->address->address1 = "123 Main St."; …
```

API Version 2.9

---

lib/recurly/invoice.php
lib/recurly/transaction.php

From the v2.9 Release Notes
- Removed deprecated singular <subscription> links. Now only plural
<subscriptions> links are returned.

Removes links to singular subscription

---

CHANGELOG.md
README.md
lib/recurly/client.php

This release will upgrade us to API version 2.10.
* API Version 2.10 [#339](https://github.com/recurly/recurly-client-php/pull/339)
* Add missing writeable fields to AddOn [#338](https://github.com/recurly/recurly-client-php/pull/338)
* Removes links to singular subscription (thanks to @phpdave) [#340](https://github.com/recurly/recurly-client-php/pull/340)
There are several breaking changes to support the new credit memos feature.
When creating invoices or using `markFailed()`, we now return an `Recurly_InvoiceCollection` object rather than an `Recurly_Invoice`. If you wish to upgrade your application without changing functionality, we recommend that you use the `charge_invoice` on the `Recurly_InvoiceCollection`. Example:
```php
$invoice = …
```

Release client 2.10.0 / API version 2.10

---

Tests/Recurly/Account_Test.php
Tests/Recurly/Adjustment_Test.php
Tests/Recurly/Purchase_Test.php
Tests/Recurly/Subscription_Test.php
Tests/fixtures/accounts/show-200.xml
Tests/fixtures/purchases/create-201.xml
Tests/fixtures/subscriptions/show-200.xml
lib/recurly/account.php
lib/recurly/adjustment.php
lib/recurly/client.php
lib/recurly/invoice.php
lib/recurly/purchase.php
lib/recurly/subscription.php

* Add preferred_locale support on Account.
* Add pause and resume support on Subscription.
* Add multi shipping address support in Purchase.

API v2.11 Changes

---

CHANGELOG.md
lib/recurly/client.php

This release will upgrade us to API version 2.11. There are no breaking changes.
* API Version 2.11 [#342](https://github.com/recurly/recurly-client-php/pull/342)

Release client 2.10.1 / API version 2.11

---

CHANGELOG.md
lib/recurly/client.php

This release will upgrade us to API version 2.12. There are no breaking changes.
* API Version 2.12 [#348](https://github.com/recurly/recurly-client-php/pull/348)

Client Release 2.10.2 / API version 2.12

---

Tests/Recurly/Invoice_Test.php
Tests/fixtures/invoices/show-200.xml
lib/recurly/invoice.php

This is part of API version 2.13. It adds the documentation for the `all_transactions` link. This link appears if there are more than 500 transactions on the invoice.

Add all_transactions link to Invoice

---

Tests/Recurly/Purchase_Test.php
lib/recurly/purchase.php

For API version 2.13. Allows programmer to set the gateway for a purchase. If this changes, I will follow up with another PR on the `api_version_2_13` branch.

Allow programmer to set gateway code in purchase

---

Tests/Recurly/Account_Test.php
Tests/Recurly/CustomFieldList_Test.php
Tests/Recurly/Subscription_Test.php
Tests/fixtures/accounts/show-200.xml
Tests/fixtures/subscriptions/show-200.xml
lib/recurly.php
lib/recurly/account.php
lib/recurly/base.php
lib/recurly/custom_field.php
lib/recurly/custom_field_list.php
lib/recurly/resource.php
lib/recurly/subscription.php

```php
// Get a field
$account->custom_fields['cat_name']->value;
// Get all fields
foreach ($account->custom_fields as $field) {
print "{$field->name} {$field->value}\n";
}
// Set a value
$field = new Recurly_CustomField();
$field->name = 'food';
$field->value = 'salsa';
$account->custom_fields[] = $field;
// or
$account->custom_fields[] = new Recurly_CustomField('food', 'ate my hamburger');
// Clear a value
$account->custom_fields['cat_name']->value = null;
// or
unset($account->custom_fields['cat_name']);
```

[TPE-2561] Support for custom fields

---

.travis.yml
README.md
composer.json

Bump the minimum version to 5.6. We will ignore failures in travis below
this version. We are also adding 7.2 to travis tests.

Update php version info

---

CONTRIBUTING.md
README.md

Using the latest version of composer from https://getcomposer.org/installer yields this message:
```You are using the deprecated option "dev". Dev packages are installed by default now.```
This removes that flag from the instructions in README.md and CONTRIBUTING.md

Remove deprecated --dev flag to composer install command instructions

---

CHANGELOG.md
Tests/Recurly/Invoice_Test.php
Tests/Recurly/Subscription_Test.php
Tests/fixtures/invoices/show-200-updated-invoice.xml
Tests/fixtures/subscriptions/show-200-changed-notes.xml
lib/recurly/address.php
lib/recurly/client.php
lib/recurly/invoice.php

This release will upgrade us to API version 2.14. There are no breaking changes.
* Update php version info [#355](https://github.com/recurly/recurly-client-php/pull/355)
* Support updating an invoice [#360](https://github.com/recurly/recurly-client-php/pull/360)
* Fix custom field serialization [#361](https://github.com/recurly/recurly-client-php/pull/361)
* Support updating custom fields through Subscription#updateNotes [#362](https://github.com/recurly/recurly-client-php/pull/362)
* Update README [#359](https://github.com/recurly/recurly-client-php/pull/359)

Bump to 2.10.4 / API version 2.14

---

scripts/build
scripts/check-deps
scripts/install-deps
scripts/test

Added `scripts` folder for a standard interface to perform common tasks

Added `scripts` folder

---

lib/recurly/response.php

Attempting to create billing information with a token may return an ambigious 404 for invalid or expired token `"token_invalid"` and missing recurly account `"not_found"`.
This fixes `Reculy_NotFoundError` to return a correct value in `getRecurlyCode()`.

provide a correct recurly code when responding with a 404

---

lib/recurly/push_notification.php

Allows you to access all the data in a webhook. Updates the notes to reflect current state of Recurly webhooks.
Below is the playground script to test the new functionality. Note that a `new_credit_payment_notification` does not actually contain all of the possible nodes, so I added them from the examples on the [docs page](https://dev.recurly.com/page/webhooks)
```php
<?php
include './scripts/php/stub.php';
$xml=<<<XML
<?xml version="1.0" encoding="UTF-8"?>
<new_credit_payment_notification>
<account>
<account_code>1234</account_code>
<username></username>
<email></email>
<first_name></first_name>
<last_name></last_name>
<company_name></company_name>
<phone></phone>
</account>
<subscription>
<plan>
<plan_code>bronze</plan_code>
<name>Bronze Plan</name>
</plan> …
```

Add missing possible childnode names

---

CHANGELOG.md
lib/recurly/client.php

This release will upgrade us to API version 2.15. There are no breaking changes.
* Added `scripts` folder [364](https://github.com/recurly/recurly-client-php/pull/364)
* Provide a correct recurly code when responding with a 404 [366](https://github.com/recurly/recurly-client-php/pull/366)
* Add support for more webhooks [368](https://github.com/recurly/recurly-client-php/pull/368)

Bump to version 2.10.5 / API version 2.15

---

Tests/Recurly/Client_Test.php
Tests/fixtures/client/bad-request-400.xml
lib/recurly/errors.php
lib/recurly/response.php

When an error comes back from the server, it has a details tag in the XML. For example:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<error>
<symbol>invalid_xml</symbol>
<description>The provided XML was invalid.</description>
<details>Unacceptable tags &lt;address&gt;</details>
</error>
```
Just stating that the provided XML was invalid is rather useless to a developer trying to fix their issues. Adding the detail of the unacceptable tag is much better.
This issue was originally highlighted by #344, which shows an example of where a developer would have been able to fix their issue more easily if they could see the details of the error.

Add details to error messages to make them more helpful

---

.gitignore
lib/recurly/addon.php
lib/recurly/base.php
lib/recurly/billing_info.php
lib/recurly/client.php
lib/recurly/coupon.php
lib/recurly/custom_field.php
lib/recurly/custom_field_list.php
lib/recurly/export_date_list.php
lib/recurly/export_file.php
lib/recurly/export_file_list.php
lib/recurly/gift_card.php
lib/recurly/invoice.php
lib/recurly/measured_unit.php
lib/recurly/pager.php
lib/recurly/plan.php
lib/recurly/purchase.php
lib/recurly/push_notification.php
lib/recurly/recurly_js.php
lib/recurly/redemption.php
lib/recurly/resource.php
lib/recurly/response.php
lib/recurly/shipping_address.php
lib/recurly/stub.php
lib/recurly/subscription.php
lib/recurly/transaction.php
lib/recurly/usage.php

Fixes #277 and fixes #358.
This PR addresses all of the errors specified by PHPStorm.

Fix errors specified by PHPStorm

---

lib/recurly/subscription.php

Fixes #313 
Playground script:
```php
<?php
// Assumes subscription "47c96143efc6c189bbf5bb47969166b4" exists on the site
include './scripts/php/stub.php';
try {
$subscription = Recurly_Subscription::get('47c96143efc6c189bbf5bb47969166b4');
$subscription->terminateWithoutRefund(false);
print "Subscription: $subscription" . "\n";
} catch (Recurly_NotFoundError $e) {
print "Subscription Not Found: $e";
} catch (Recurly_Error $e) {
print "Subscription already terminated: $e";
}
```

Add charge parameter to subscription termination functions

---

Tests/Recurly/Account_Test.php
lib/recurly/account.php

As per documentation in https://dev.recurly.com/docs/create-an-account `account_acquisition` parameter is missing in writeable attribute array.
Additional note: there seems to be a mismatch between the client and the documentation concerning `shipping_address` attribute, not sure which is correct.

Added missing account_acquisition to writable attributes

---

Tests/Recurly/Pager_Test.php
Tests/fixtures/pager/index-empty-200.xml
Tests/fixtures/pager/show-empty-200.xml
lib/recurly/pager.php

Fixes #354 
Script:
```php
// 'account' should be a valid account with canceled subscriptions but no live subscriptions
$subscriptions = Recurly_SubscriptionList::getForAccount('account', ['state' => 'live']);
print $subscriptions->count() . "\n";
$sub = $subscriptions->current();
var_dump($sub);
```
Before this commit, this script would throw an exception. Now it prints
```
0
NULL
```

Fix pager->current() breaking when no data

---

CHANGELOG.md
lib/recurly/client.php

This release will upgrade us to API version 2.16. There are no breaking changes.
* Added `details` to error messages [372](https://github.com/recurly/recurly-client-php/pull/372)
* Added `charge` parameter to subscription termination functions [374](https://github.com/recurly/recurly-client-php/pull/374)
* Fixed errors reported by PHPStorm [375](https://github.com/recurly/recurly-client-php/pull/375)
* Added `account_acquisition` attribute to `account` [377](https://github.com/recurly/recurly-client-php/pull/377)
* Fixed pager so it does not break when there is no data [378](https://github.com/recurly/recurly-client-php/pull/378)

Bump to version 2.10.6 / API version 2.16

---

Tests/Recurly/Invoice_Test.php
Tests/Recurly/Subscription_Test.php
Tests/fixtures/subscriptions/show-200-changed-notes.xml
lib/recurly/invoice.php
lib/recurly/subscription.php

Allows `gateway_code` to be updated via the `subscription/notes` endpoint and the `PUT invoice` endpoint
Scripts:
```php
<?php
// Assumes subscription uuid "46c7ddb06e35530669baa445e3926e34" exists
include './scripts/php/stub.php';
$uuid = '46c7ddb06e35530669baa445e3926e34';
$sub = Recurly_Subscription::get($uuid);
$sub->updateNotes(array("gateway_code" => "jvkvq2er456m");
print("\n");
```
```php
$invoice = Recurly_Invoice::get('1001');
$invoice->gateway_code = 'jvm7ol289raz';
$invoice->update();
```

Add gateway_code to subscription and invoice

---

Tests/Recurly/Base_Test.php
lib/recurly/base.php

Added new method getHeaders(), which will allow to get all response headers after each API call, without sending any extra request
fixed issue #276

Added new method getHeaders(), which will allow to get all response headers after each API call

---

CHANGELOG.md
README.md
Tests/Recurly/Account_Test.php
Tests/Recurly/Invoice_Test.php
Tests/Recurly/Subscription_Test.php
Tests/fixtures/accounts/show-200.xml
Tests/fixtures/subscriptions/show-200-changed-notes.xml
lib/recurly/account.php
lib/recurly/client.php
lib/recurly/invoice.php
lib/recurly/subscription.php

This release will upgrade us to API version 2.17.
* Add `gateway_code` to Subscription and Invoice objects [PR](https://github.com/recurly/recurly-client-php/pull/380)
* Add `exemption_certificate` to Account object [PR](https://github.com/recurly/recurly-client-php/pull/381)
* Remove deprecated JS module [PR](https://github.com/recurly/recurly-client-php/pull/382)
* Add `getHeaders()` method [PR](https://github.com/recurly/recurly-client-php/pull/383)
* Add OpenSSL version to user agent [PR](https://github.com/recurly/recurly-client-php/pull/384)
This release contains one breaking change. Older Recurly.js token signing is not longer supported. You should upgrade to version 4 of Recurly.js: https://dev.recurly.com/docs/recurlyjs

Release version 2.11.0 / API version 2.17

---

CHANGELOG.md

Fixes #387 
I've also added this to the release notes here: https://github.com/recurly/recurly-client-php/releases/tag/2.10.0

Add missing breaking change in 2.10 changelog

---

README.md

This makes the README explicit that problems may be experienced when attempting to use an old, unsupported version of OpenSSL.

Add note about OpenSSL support to README

---

Tests/bootstrap.php
lib/recurly/client.php
lib/recurly/coupon.php
lib/recurly/pager.php
lib/recurly/response.php

Changes Recurly_Client to always force HTTP header keys in to lowercase before storing in Recurly_Response.

Handle HTTP headers in a more case insensitive way

---

Tests/Recurly/Billing_Info_Test.php
Tests/fixtures/billing_info/show-amazon-200.xml

Adds an assert to verify that the new `amazon_region` will work with Billing Info objects.
```php
<?php
try {
$billing_info->account_code       = 'x';
$billing_info->first_name         = 'John';
$billing_info->last_name          = 'Du Monde';
$billing_info->address1           = '123 Paper Street';
$billing_info->city               = 'Los Angeles';
$billing_info->state              = 'CA';
$billing_info->zip                = '95312';
$billing_info->country            = 'US';
$billing_info->phone              = '213-555-5555';
$billing_info->amazon_billing_agreement_id = 'C01-1234567-8901234';
$billing_info->amazon_region      = 'us';
$billing_info->create();
print "Billing Info: $billing_info";
} catch (Recurly_ValidationError $e) {
// The amazon …
```

Add amazon_region to Billing Info

---

Tests/Recurly/Account_Test.php
Tests/fixtures/accounts/hierarchy/create-201.xml
Tests/fixtures/accounts/hierarchy/show-child-200.xml
Tests/fixtures/accounts/hierarchy/show-parent-200.xml
Tests/fixtures/accounts/hierarchy/update-200.xml
Tests/fixtures/accounts/hierarchy/update-no-parent-200.xml
lib/recurly/account.php

This adds support for account hierarchy. Tests only include operations on the account object because there is no change in the response to create subscription and create purchase endpoints. Examples of this usage are included below.
Create an account with a parent account:
```php
try {
$account = new Recurly_Account('example-123');
$account->parent_account_code = 'example-124';
$account->create();
} catch (Recurly_ValidationError $e) {
print "Invalid Account: $e";
}
```
Get a parent account:
```php
$accountCode = 'example-123';
try
{
$account = Recurly_Account::get($accountCode);
$parent = $account->parent_account->get();
print($parent);
}
catch(Recurly_Error $e)
{
print("Caught an error:\n");
print($e);
}
print("\n");
```
Get child accounts:
```php
$accountCode = 'example-124';
try
{ …
```

Add support for account hierarchy

---

CHANGELOG.md
lib/recurly/client.php

* Adds missing properties to BillingInfo [PR](https://github.com/recurly/recurly-client-php/pull/395)
* Handle HTTP headers in a case insensitive way [PR](https://github.com/recurly/recurly-client-php/pull/392)
* Add OpenSSL support note to README [PR](https://github.com/recurly/recurly-client-php/pull/390)
* Add Capture and Cancel Purchase endpoints [PR](https://github.com/recurly/recurly-client-php/pull/386) and [PR](https://github.com/recurly/recurly-client-php/pull/389)

Bump to version 2.11.1

---

.travis.yml
README.md

HHVM no longer supports Composer or PHP as of version 4.0.0. More information can be found in their blog. https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html

Specify which versions of HHVM we should test in travis

---

lib/recurly/client.php

The getPdf and getFile methods are not currently reporting which version they need. This adds the version header so when API versions are deprecated, these methods will still work.

Add X-Api-Version header to getPdf and getFile

---

CHANGELOG.md
Tests/Recurly/Billing_Info_Test.php
Tests/fixtures/billing_info/show-amazon-200.xml
lib/recurly/base.php
lib/recurly/client.php
lib/recurly/push_notification.php
lib/recurly/response.php

* Adds support for Amazon Region [PR](https://github.com/recurly/recurly-client-php/pull/394)
* Add note about HHVM support [PR](https://github.com/recurly/recurly-client-php/pull/399)
* Adds X-API-Version header to getPdf() and getFile() in the client [PR](https://github.com/recurly/recurly-client-php/pull/398)

Release version 2.11.2 / API version 2.18

---

CHANGELOG.md
Tests/Recurly/Account_Test.php
Tests/Recurly/ExportFile_Test.php
Tests/fixtures/accounts/hierarchy/create-201.xml
Tests/fixtures/accounts/hierarchy/show-child-200.xml
Tests/fixtures/accounts/hierarchy/show-parent-200.xml
Tests/fixtures/accounts/hierarchy/update-200.xml
Tests/fixtures/accounts/hierarchy/update-no-parent-200.xml
lib/recurly/account.php
lib/recurly/base.php
lib/recurly/client.php
lib/recurly/export_file.php

This brings us up to API version 2.19
* Adds support for Account Hierarchy [PR](https://github.com/recurly/recurly-client-php/pull/393)
* Ensure that the client can only connect to recurly domains to improve security [878e844](https://github.com/recurly/recurly-client-php/pull/401/commits/878e8444ad7aa675fed956d610e8c44158787047)
If you are using the `Recurly_ExportFile` class, you must now use `getDownloadUrl()` to get the download url rather than accessing this property directly.
```php
$url = $export_file->download_url;
$url = $export_file->getDownloadUrl();
```
If you are using `$export_file->download($fp)` and not accessing the url directly, you should not be affected.

Release version 2.12.0 / API version 2.19

---

lib/recurly/client.php

The new method to verify the domain that a request is being made to breaks when there is a subdomain (which is most of the time). This PR removes the subdomain so that it is just verifying the domain is whitelisted.

Fix broken _verifyUri method

---

CHANGELOG.md
lib/recurly/client.php

* Fix issue with _verifyUri [PR](https://github.com/recurly/recurly-client-php/pull/402)

Release version 2.12.1

---

lib/recurly/base.php

Hello,
I encountered an issue where I use a mock client of recurly during test runs where the client does not get passed down to all sub objects.
For instance if I fetch an invoice like this:
```
$invoice = \Recurly_Invoice::get($invoiceNumber, new MockClient());
```
if this gets called for an invoice that contains `credit_payments` then all the `\Recurly_Stub` object on the individual `\Recurly_CreditPayment` do not have the `MockClient` set as `_client` but instead have the default `\RecurlyClient` set.

Fix: pass client to objects in an array

---

lib/recurly/client.php

Per https://github.com/recurly/recurly-client-php/pull/408#discussion_r274803159, this makes the `$apiUrl` property private and allows you to access the value via a read only method like so:
```php
print(Recurly_Client::apiUrl() . "\n");
```

Make API url private

---

CHANGELOG.md
lib/recurly/client.php

* Ensure nested resources have the same client as their parent [PR](https://github.com/recurly/recurly-client-php/pull/409)
* Make `Recurly_Client::$apiUrl` private [PR](https://github.com/recurly/recurly-client-php/pull/410)

Release version 2.12.2

---

lib/recurly/subscription.php

This adds support for updating the subscription at next bill date rather than just immediately or at renewal.
```php
<?php
$uuid = '4c2a90c55cfe520e7f33744dc09ae922';
$sub = Recurly_Subscription::get($uuid);
$sub->plan_code = "silver";
$sub->updateAtNextBillDate();
```

Add support for updating a subscription at next bill date

---

lib/recurly/billing_info.php

This allows the client to use the new 3DSecure features of the API. This involves a 2 step flow with RecurlyJS, see https://github.com/recurly/recurly-js/pull/527 for technical details on that side of this process.
Script 1: Attempt to update a billing info with a credit card that requires 3DS authentication:
```php
try {
$billing_info->account_code       = 'x';
$billing_info->first_name         = 'John';
$billing_info->last_name          = 'Du Monde';
$billing_info->address1           = '123 Paper Street';
$billing_info->city               = 'Los Angeles';
$billing_info->state              = 'CA';
$billing_info->zip                = '95312';
$billing_info->country            = 'US';
$billing_info->phone              = '213-555-5555'; …
```

Add 3DS tokens to transaction error and billing info

---

CHANGELOG.md
lib/recurly/billing_info.php
lib/recurly/client.php

This brings us up to API version 2.21. There are no breaking changes
* Add 3DS authentication [PR](https://github.com/recurly/recurly-client-php/pull/415)

Release version 2.12.4

---

Tests/Recurly/Account_Test.php
Tests/Recurly/Billing_Info_Test.php
Tests/Recurly/Invoice_Test.php
Tests/Recurly/Purchase_Test.php
lib/recurly/account.php
lib/recurly/billing_info.php
lib/recurly/client.php
lib/recurly/invoice.php
lib/recurly/purchase.php
lib/recurly/subscription.php

As a part of PSD2, there is an exemption to exclude MOTO transactions from SCA scope.
In order to pass this indicator to the gateways, merchants need a mechanism via API
to inform Recurly of these transactions. These transactions will be initiated from
within a merchants customer service / support admin portal UI, where the customer
is not authenticated to be able to complete an SCA flow.
This is exposed to the programmer as `transaction_type` on many of the resources. Set the value to `moto` to mark the transaction as MOTO. Ex use with purchases:
```php
$purchase = new Recurly_Purchase();
$purchase->currency = 'USD';
$purchase->transaction_type = 'moto';
$purchase->account = new Recurly_Account();
$purchase->account->account_code = 'aba9209a-aa61-4790-8e61-0a2692435fee';
$subscription = …
```

Moto transactions

---

lib/recurly/base.php
lib/recurly/client.php
lib/recurly/push_notification.php
lib/recurly/response.php

Disabling the Entity Loader was a great idea
https://github.com/recurly/recurly-client-php/commit/a7e08334
However, this wreaked havoc for me for other code on the site that tries to load xml files.
This patch may be a bit ham-fisted, but it corrects the problem on my sites and I hope you'll consider including it or a similar fix in future versions.

Restore libxml state when changed

---

CHANGELOG.md
lib/recurly/client.php

* Support billing_info on Subscription, Invoice & Gift card [PR](https://github.com/recurly/recurly-client-php/pull/424)
* PSD2 billing info changes [PR](https://github.com/recurly/recurly-client-php/pull/426)
* Restore libxml state when changed [PR](https://github.com/recurly/recurly-client-php/pull/423)

Release 2.12.6

---

Tests/Recurly/Purchase_Test.php
lib/recurly/purchase.php

- Added 'shipping_address' as a writeable attribute 
- Amended 'Purchase_Test.php' to account for 'shipping_address' as Purchase attribute instead of Account attribute

Add shipping address to Purchase

---

Tests/Recurly/Subscription_Test.php
lib/recurly/subscription.php

Subscription#update, Subscription#preview and Subscription#cancel
have changes in the timeframe parameters.
Subscription#update and Subscription#preview have been updated to no longer accept the "renewal" value for timeframe. This will
continue to work but is deprecated which means Subscription#updateAtRenewal is also deprecated. Instead, merchants will be able to send a timeframe value of "bill_date" or "term_end".
These timeframes are aligned to "current_period_ends_at" and "current_term_ends_at", respectively.
Subscription#cancel has been updated to optionally accept the "timeframe" parameter. It accepts values of "bill_date" or "term_end".

Subscription timeframe changes

---

Tests/Recurly/Item_Test.php
Tests/fixtures/items/destroy-204.xml
Tests/fixtures/items/reactivate-200.xml
Tests/fixtures/items/show-200.xml
lib/recurly.php
lib/recurly/adjustment.php
lib/recurly/base.php
lib/recurly/client.php
lib/recurly/item.php
lib/recurly/item_list.php

Add Item class to PHP Client Library
To create an item:
```PHP
$item = new Recurly_Item();
$item->item_code = 'little_llama';
$item->name = 'Little Llama';
$item->create();
```
To list all items:
```PHP
$items = Recurly_ItemList::get();
foreach ($items as $item) {
print "Item: $item->name\n";
}
```
To look up an item (item_code required):
```php
$item = Recurly_Item::get('little_llama');
```
To update an item (item_code required):
```php
$item = Recurly_Item::get('little_llama');
$item->description = 'An item description';
$item->update();
```
To delete an item (item_code required):
```php
$item = Recurly_Item::get('little_llama');
$item->delete();
```
To restore an item (item_code required):
```php
$item = Recurly_Item::get('little_llama');
$item->reactivate();
```
To create an …

Add Item class

---

Tests/Recurly/ShippingAddress_Test.php
lib/recurly/shipping_address.php

`vatNumber` is a supported attribute for `ShippingAddress` but has not yet been included in the PHP client library. This PR addresses that issue.

Add vat_number to ShippingAddress class

---

Tests/bootstrap.php
phpunit.xml.dist

This PR simplifies the PHPUnit configuration in the following ways:
- Configure PHP INI settings in `phpunit.xml.dist`, not the `Tests/bootstrap.php` file.
- Remove a lot of older, unneeded attributes from the `<phpunit>` element
Additionally, I've whitelisted files for generating code coverage reports.

Simplify the PHPUnit configuration

---

CHANGELOG.md
Tests/Recurly/Base_Test.php
lib/recurly/client.php

Release 2.12.10
* Add vat_number to ShippingAddress class (https://github.com/recurly/recurly-client-php/pull/443)
* Update the documentation and testing matrix for current PHP releases (https://github.com/recurly/recurly-client-php/pull/445)
* Simplify the PHPUnit configuration (https://github.com/recurly/recurly-client-php/pull/446)
* Ensure PHP 7.4 compatibility (https://github.com/recurly/recurly-client-php/pull/449)

Release 2.12.10

---

lib/recurly/client.php

Addresses [issue 453](https://github.com/recurly/recurly-client-php/issues/453).
- Removed `verifyUri` from `getFile`, which will allow external domains, e.g. s3.amazonaws.com
We've determined it's safe to remove this check because getFile is limited to calls that are not processed by the client and getFile does not send authentication or PII details to it's target server. Futhermore, the URL comes from Recurly's response so we can reasonably assume it will be safe to invoke. Removing this check allows us to change the downloads in the future if they move from s3.

Allow external domains for getFile() calls

---

Tests/Recurly/ShippingAddress_Test.php
Tests/fixtures/shipping_addresses/destroy-204.xml
lib/recurly/shipping_address.php

- Add `delete` function to ShippingAddress object
- Add unit test 
To delete a shipping address by id (id = 2922857578120715120 in this example):
```
$shipping_addresses = Recurly_ShippingAddressList::get($account->account_code);
foreach ($shipping_addresses as $address) {
if ($address->id == 2922857578120715120){
$address->delete();
}
}
```
To delete all shipping addresses associated with account:
```
$shipping_addresses = Recurly_ShippingAddressList::get($account->account_code);
foreach ($shipping_addresses as $address) {
$address->delete();
} 
```

Add 'Delete' to ShippingAddress object

---

lib/recurly/adjustment.php

To fetch `external_sku`:
```
$charge = new Recurly_Adjustment();
$charge->account_code = 'account_code'
$charge->unit_amount_in_cents = 5000; 
$charge->currency = 'USD';
$charge->quantity = 1;
$charge->item_code = 'item_code'
$charge->create();
print("Adjustment: $charge->external_sku");
```

Add external_sku to Adjustment

---

Tests/Recurly/Subscription_Test.php
Tests/fixtures/subscriptions/convert-trial-200.xml
Tests/fixtures/subscriptions/show-200-trial.xml
lib/recurly/subscription.php

To convert trial to paid subscription with 3DS Token:
```php
$subscription->convertTrial(token);
```
To convert trial for non-3ds where subscription has billing info:
```php
$subscription->convertTrial();
```
To convert trial to paid subscription with transaction type:
```php
$subscription->convertTrialMoto();
```

Add convertTrial() to Subscription

---

CHANGELOG.md
lib/recurly/client.php

This brings us up to API version 2.25. There are no breaking changes
* Allow external domains for `getFile()` calls (https://github.com/recurly/recurly-client-php/pull/454)
* Cleanup old upgrade warning (https://github.com/recurly/recurly-client-php/pull/455)
* Add 'Delete' to ShippingAddress object (https://github.com/recurly/recurly-client-php/pull/457)
* Add `external_sku` to Adjustment (included in API version 2.24)  (https://github.com/recurly/recurly-client-php/pull/458)
* Add `convertTrial()`to Subscription  (https://github.com/recurly/recurly-client-php/pull/459)

Release 2.12.11

---

lib/recurly/transaction.php

Hello,
I adjusted the properties returned by the list transactions endpoint. Looks like error properties are now sent as a Recurly_TransactionError. I also add some other missing properties.
Note: the transaction_error seems to be incorrect in the documentation as well: https://dev.recurly.com/docs/transaction-object

Transaction: update phpdoc

---

Tests/Recurly/Subscription_Test.php
lib/recurly/account.php
lib/recurly/resource.php

- When new Purchase is created with an existing account, account's address field will not be overwritten with blank values when a new address is not specified.
- When the existing account's address is changed with the new Purchase is created (rare), the account's address will be updated with the new fields.

Prevent overwritten address on new purchase with existing account

---

Tests/Recurly/Addon_Test.php
lib/recurly/addon.php

To create item-backed add-on:
```php
$add_on = new Recurly_Addon();
$add_on->plan_code = $plan->plan_code;
$add_on->item_code = $item->item_code;
$add_on->unit_amount_in_cents->addCurrency('USD', 400);
$add_on->create();
```
To get item-backed add-on:
```php
Recurly_Addon::get($plan->plan_code, $item->item_code);
```
To update item-backed add-on:
```php
$add_on->unit_amount_in_cents['USD'] = 200;
$add_on->update();
```
When add-on has an associated item, only the following attributes are updatable:
```php
unit_amount_in_cents
default_quantity
display_quantity_on_hosted_page
optional
```

Add additional attributes to support item-backed add-ons

---

CHANGELOG.md
lib/recurly/client.php

* Transaction: update phpdoc (https://github.com/recurly/recurly-client-php/pull/460)
* Update api version to 2.25 (https://github.com/recurly/recurly-client-php/pull/463)
* Moving statusCode checks (https://github.com/recurly/recurly-client-php/pull/469)
* Prevent overwritten address on new purchase with existing account (https://github.com/recurly/recurly-client-php/pull/470)
* Add additional attributes to support item-backed add-ons (https://github.com/recurly/recurly-client-php/pull/474)

Release 2.12.12

---

Tests/Recurly/Billing_Info_Test.php
Tests/fixtures/billing_info/show-sepa-200.xml
lib/recurly/billing_info.php
lib/recurly/client.php

This feature is to allow support of the IBAN field in our V2 API for the applicable endpoints. This field is most similar to banking account information or credit card information, and is used to make payments for SEPA transactions.
IBAN numbers can be set in all endpoints that support BillingInfo:
PUT "/v2/accounts/{account_id}/billing_info"
PUT "/v2/accounts/{account_id}"
POST "/v2/accounts"
POST "/v2/subscriptions"
POST "/v2/purchases"
POST "/v2/purchases/preview"
A sample request payload is provided below:
```
<billing_info>
<iban>IBANNUMBERHERE</iban>
<name_on_account>Verena Example</name_on_account>
<!-- address fields... ->
</billing_info>
```

Add IBAN attribute to BillingInfo

---

lib/recurly/base_client.php
lib/recurly/http_adapter.php
tests/mock_client.php

Adds the `Accept-Encoding: gzip` header to the request and decodes gzipped responses where appropriate.
When requesting ~4500 transactions using the `list_transactions` method, there was ~18% speed improvement and the overall payload size was reduced by ~600%

Enable gzip compression on HTTP responses

---

.bumpversion.cfg
composer.json
lib/recurly/version.php

[Full Changelog](https://github.com/recurly/recurly-client-php/compare/3.0.0...HEAD)
- Enable gzip compression on HTTP responses [\#475](https://github.com/recurly/recurly-client-php/pull/475) ([douglasmiller](https://github.com/douglasmiller))
- Fri Mar 20 17:48:03 UTC 2020 Upgrade API version v2019-10-10 [\#480](https://github.com/recurly/recurly-client-php/pull/480) ([douglasmiller](https://github.com/douglasmiller))
- Adding release scripts [\#478](https://github.com/recurly/recurly-client-php/pull/478) ([douglasmiller](https://github.com/douglasmiller))
- Reducing minimum php version from 7.3 to 7.2 [\#473](https://github.com/recurly/recurly-client-php/pull/473) ([douglasmiller](https://github.com/douglasmiller))
- Adding …

Release 3.0.1

---

Tests/Recurly/Addon_Test.php
lib/recurly/addon.php
lib/recurly/base.php
lib/recurly/client.php
lib/recurly/tier.php

To create add-on with tiered pricing:
```php
$add_on = new Recurly_Addon();
$add_on->plan_code = $plan->plan_code;
$add_on->add_on_code = 'plant';
$add_on->name = 'Plant';
$add_on->tier_type = 'tiered';
$tier1 = new Recurly_Tier();
$tier1->unit_amount_in_cents->addCurrency('USD', 400);
$tier1->ending_quantity = 800;
$tier2 = new Recurly_Tier();
$tier2->unit_amount_in_cents->addCurrency('USD', 200);
$add_on->tiers = array($tier1, $tier2);
$add_on->create();
```

Tiered pricing

---

lib/recurly/billing_info.php

A mandate reference is a specific ID used in a payment system to show that an agreement was made between the customer and the merchant. It is often required for compliance reasons to display when a billing info is created or a payment is created.

Add mandate_reference attribute to BillingInfo

---

CHANGELOG.md
lib/recurly/client.php

This brings us up to API version 2.26. There are no breaking changes
* Add IBAN attribute to BillingInfo [PR](https://github.com/recurly/recurly-client-php/pull/476)
* Tiered pricing [PR](https://github.com/recurly/recurly-client-php/pull/482)
* Add mandate_reference attribute to BillingInfo [PR](https://github.com/recurly/recurly-client-php/pull/483)

Release 2.12.13

---

.bumpversion.cfg
composer.json
lib/recurly/version.php

[Full Changelog](https://github.com/recurly/recurly-client-php/compare/3.0.1...HEAD)
- Tue Apr 14 20:57:43 UTC 2020 Upgrade API version v2019-10-10 [\#492](https://github.com/recurly/recurly-client-php/pull/492) ([douglasmiller](https://github.com/douglasmiller))
- Included the to-be released changes in the changelog [\#491](https://github.com/recurly/recurly-client-php/pull/491) ([douglasmiller](https://github.com/douglasmiller))
- Adding phpDocumentor and ./scripts/docs [\#489](https://github.com/recurly/recurly-client-php/pull/489) ([douglasmiller](https://github.com/douglasmiller))
- Updating release script to be uniform across all clients [\#487](https://github.com/recurly/recurly-client-php/pull/487) ([douglasmiller](https://github.com/douglasmiller))
- Thu …

Release 3.1.0

---

lib/recurly/base_client.php
tests/BaseClient_Test.php

Adding a validation method that will ensure that path parameters are not empty strings to address issues where a `get_*` operation (`/resources/{resource_id}`) does not get handled by the API as a `list_*` operations (`/resources/`).

Ensure that path parameters are not empty strings

---

.bumpversion.cfg
composer.json
lib/recurly/version.php

[Full Changelog](https://github.com/recurly/recurly-client-php/compare/3.1.0...HEAD)
**Fixed bugs:**
- Parsing 'false' as null inside the v3 API [\#495](https://github.com/recurly/recurly-client-php/issues/495)
- Make returns nullable [\#496](https://github.com/recurly/recurly-client-php/pull/496) ([bhelx](https://github.com/bhelx))
- Ensure that path parameters are not empty strings [\#494](https://github.com/recurly/recurly-client-php/pull/494) ([douglasmiller](https://github.com/douglasmiller))

Release 3.1.1

---

scripts/test

This should result in a slight speed increase in the CI pipeline when running the tests.

[Internal] Disabling 'composer dump-autoload' in codefresh

---

Tests/Recurly/Subscription_Test.php
Tests/fixtures/subscriptions/show-200-QBP.xml
lib/recurly/tier.php

Reported issue: When using the subscription_update call, a plan with tiered pricing will fail, with an error requesting additional parameters not specified in API Request. 
Expected result: Subscription should update, regardless of tiered add-on state.
Actual result: Subscription will fail to update, with errors around tiers, unit_amount_in_cents and tier_quantity.
Sample xml: 
```xml
<subscription>
<timeframe>now</timeframe>
<subscription_add_ons>
<subscription_add_on>
<add_on_code>muppy</add_on_code>
<quantity>3</quantity>
<revenue_schedule_type>evenly</revenue_schedule_type>
<tier_type>tiered</tier_type>
<tiers>
<tier></tier>
<tier></tier>
</tiers>
</subscription_add_on>
</subscription_add_ons>
<collection_method>automatic</collection_method>
<custom_fields></custom_fields> …
```

Include tier attributes in request body

---

lib/recurly/adjustment.php

$refund_apply_order argument in Recurly_Adjustment::refund method is set to string 'credit'. 
The API responds with an error "Invalid refund_method (must be one of transaction_first, credit_first, all_transaction, all_credit)"
Recurly_Invoice::function argument however $refund_method is set to 'credit_first'
therefore I found this error when doing refunds with the following use-case 
```
$adjustment = \Recurly_Adjustment::get('53f47d7....');
$adjustment->refund();
```
Thanks

default parameter gives error

---

lib/recurly/base_client.php
tests/BaseClient_Test.php

Automatically converts `DateTime` objects that are passed in as body or query string parameters to their ISO8601 string format.

Convert DateTime objects to ISO8601 strings

---

Tests/Recurly/Billing_Info_Test.php
Tests/fixtures/billing_info/show-bacs-200.xml
lib/recurly/billing_info.php
lib/recurly/client.php

Added `sort_code` and `type` fields to support BACS payment type.

BACS support

---

lib/recurly/http_adapter.php

Recurly API requires that the `Content-Length` header be specified according to the HTTP specification.
A subset of requests were failing with a HTTP Status Code `411` error: `411. That’s an error. POST requests require a Content-length header. That’s all we know.`

Fix HTTP 411 error by including Content-Length header

---

Tests/Recurly/Subscription_Test.php
Tests/fixtures/subscriptions/show-200.xml
lib/recurly/plan.php
lib/recurly/subscription_addon.php

This PR adds support for items on subscriptions, where merchants may now associate a subscription add-on with an item in their catalog.
`allow_any_item_on_subscriptions` has been added to the `Plan` class. It is used to determine whether items can be assigned as add-ons to individual subscriptions. If `true`, items can be assigned as add-ons to individual subscription add-ons. If `false`, only plan add-ons can be used.
`add_on_source`, added to the `SubscriptionAddOn` class, is used to determine where the associated add-on data is pulled from. If this value is set to `plan_add_on` or left blank, then add-on data will be pulled from the plan's add-ons. If the associated  `plan` has `allow_any_item_on_subscriptions` set to `true` and this field is set to `item`, then the associated add-on …

Support items on subscriptions

---

.bumpversion.cfg
composer.json
lib/recurly/version.php

[Full Changelog](https://github.com/recurly/recurly-client-php/compare/3.2.0...HEAD)
- Mon Jun 29 17:06:38 UTC 2020 Upgrade API version v2019-10-10 [\#510](https://github.com/recurly/recurly-client-php/pull/510) ([douglasmiller](https://github.com/douglasmiller))
- Convert DateTime objects to ISO8601 strings [\#504](https://github.com/recurly/recurly-client-php/pull/504) ([douglasmiller](https://github.com/douglasmiller))
**Fixed bugs:**
- Fix HTTP 411 error by including Content-Length header [\#509](https://github.com/recurly/recurly-client-php/pull/509) ([douglasmiller](https://github.com/douglasmiller))

Release 3.3.0

---

CHANGELOG.md
lib/recurly/client.php

This brings us up to API version 2.27. There are no breaking changes
* Use helper method to safeguard against empty path parameters https://github.com/recurly/recurly-client-php/pull/498
* Include tier attributes in request body https://github.com/recurly/recurly-client-php/pull/500
* Default parameter gives error https://github.com/recurly/recurly-client-php/pull/503
* BACS support https://github.com/recurly/recurly-client-php/pull/505
* Support items on subscriptions https://github.com/recurly/recurly-client-php/pull/508

Release 2.12.14

---

Tests/Recurly/Billing_Info_Test.php
Tests/fixtures/billing_info/show-becs-200.xml
lib/recurly/billing_info.php
lib/recurly/client.php

Completed:
- Added `bsb_code` field
- Included test
Affects the following endpoints:
- `PUT /v2/accounts/{account_id}/billing_info`
- `PUT /v2/accounts/{account_id}`
- `POST /v2/accounts`
- `POST /v2/purchases`
- `POST /v2/purchases/preview`
- `POST /v2/subscriptions`
To create billing_info with BECS:
```php
$billingInfo = new Recurly_BillingInfo();
$billingInfo->account_code       = $accountCode;
$billingInfo->address1           = '123 Paper Street';
$billingInfo->city               = 'Adelaide';
$billingInfo->zip                = 'W1K 6AH';
$billingInfo->country            = 'AU';
$billingInfo->phone              = '213-555-5555';
$billingInfo->name_on_account    = 'BECS account name';
$billingInfo->account_number     = '11223311';
$billingInfo->bsb_code           = '082-082'; …
```

BECS support

---

CHANGELOG.md
Tests/Recurly/Billing_Info_Test.php
Tests/fixtures/billing_info/show-becs-200.xml
lib/recurly/billing_info.php
lib/recurly/client.php

This brings us up to API version 2.28. There are no breaking changes
* BECS support https://github.com/recurly/recurly-client-php/pull/520

Release 2.12.15

---

lib/recurly/base_client.php
lib/recurly/client.php
lib/recurly/pager.php
lib/recurly/request.php
lib/recurly/response.php
tests/BaseClient_Test.php
tests/Pager_Test.php
tests/RecurlyError_Test.php
tests/RecurlyResource_Test.php
tests/Request_Test.php
tests/Response_Test.php
tests/bootstrap.php
tests/mock_client.php

This is an update to the `4.x` version of the client.
Operations now require that query string parameters be specified under the `params` key of the `$options` parameter. This will allow for additional options to be specified in requests. Currently, this only includes custom headers, but may be expanded in the future.
This pull request also adds the `getRequest()` method to the `\Recurly\Response` class for debugging purposes.
In the `3.x` version of the client, query string parameters would be specified directly on the `$options` parameter of the operation:
```php
$options = [
'limit' => 200
];
$accounts = $client->listAccounts($options);
```
With this update, the `params` key must be added to the `$options`. Additionally, a `headers` key may be added:
```php
$options = [
'params' => [ …
```

Updating operations to accept generic request options instead of just query parameters

---

lib/recurly/recurly_resource.php

This update adds a null check to the `cast` method when casting arrays. There are scenarios where the values of an array can be `null` which was causing the below warning to be thrown. 
```
PHP Warning:  First parameter must either be an object or the name of an existing class in /app/clients/php/lib/recurly/recurly_resource.php on line 113
PHP Stack trace:
PHP   1. {main}() /app/scripts/v2019-10-10/php/sandbox/preview_purchase.php:0
PHP   2. TestClient->previewPurchase() /app/scripts/v2019-10-10/php/sandbox/preview_purchase.php:37
PHP   3. TestClient->makeRequest() /app/clients/php/lib/recurly/client.php:2324
PHP   4. Recurly\Response->toResource() /app/clients/php/lib/recurly/base_client.php:44
PHP   5. Recurly\RecurlyResource::fromResponse() /app/clients/php/lib/recurly/response.php:57 …
```

Null checking variable before calling property_exists to prevent Warning

---

.bumpversion.cfg
composer.json
lib/recurly/version.php

[Full Changelog](https://github.com/recurly/recurly-client-php/compare/3.4.0...HEAD)
- Latest Changes for 2019-10-10 \(usage, measured units, etc\) [\#527](https://github.com/recurly/recurly-client-php/pull/527) ([bhelx](https://github.com/bhelx))
**Fixed bugs:**
- Warning in recurly\_resource.php @ line 113 [\#524](https://github.com/recurly/recurly-client-php/issues/524)
- Null checking variable before calling property\_exists to prevent Warning [\#525](https://github.com/recurly/recurly-client-php/pull/525) ([douglasmiller](https://github.com/douglasmiller))
- Updates array syntax to modern format [\#521](https://github.com/recurly/recurly-client-php/pull/521) ([douglasmiller](https://github.com/douglasmiller))
- Mon Jul  6 …

Release 3.5.0

---

lib/recurly/client.php
lib/recurly/resources/coupon.php
lib/recurly/resources/export_dates.php
lib/recurly/resources/export_file.php
lib/recurly/resources/export_files.php
lib/recurly/resources/unique_coupon_code.php
lib/recurly/resources/usage.php
openapi/api.yaml

* Adds `getExportDates` and `getExportFiles` operations for the [Automated Exports](https://developers.recurly.com/api/v2019-10-10/index.html#tag/automated_exports) feature.
* Adds `ExportDates`, `ExportFiles`, and `ExportFile` resources to support the `Automated Exports` feature.
* Adds `getBulkCouponCode` and `getBulkCouponId` methods to the `UniqueCouponCode` and `Coupon` resources.
* Adds `getUnitAmount` and `getUsagePercentage` methods to the `Usage` resource.

Latest Changes for 2019-10-10 (Automated Exports, additional resource data methods)

---

lib/recurly/response.php

According to section 4.2 of [RFC 2616](https://www.ietf.org/rfc/rfc2616.txt):
> Each header field consists of a name followed by a colon (":") and the field value. Field names are case-insensitive.
The PHP 3.x client libraries are not compliant with the RFC and are being updated to handle headers in a case-insensitive manner.

Updating to be compliant with RFC 2616

---

.travis.yml
CHANGELOG.md
Tests/Recurly/Pager_Test.php
Tests/bootstrap.php
lib/recurly/client.php
lib/recurly/coupon.php
lib/recurly/pager.php
lib/recurly/response.php

According to section 4.2 of [RFC 2616](https://www.ietf.org/rfc/rfc2616.txt):
> Each header field consists of a name followed by a colon (":") and the field value. Field names are case-insensitive.
This update will make the client treat headers in a case-insensitive manner.

Updating client to be compliant with RFC 2616: case-insensitive headers

---

README.md
lib/recurly/base_client.php
lib/recurly/logger.php
lib/recurly/response.php
phpunit.xml.dist
tests/BaseClient_Test.php
tests/Logger_Test.php
tests/Pager_Test.php
tests/mock_client.php

Adds the ability to specify a custom logger that implements the `PSR-3 Logger Interface`.
By default, the PHP client will use it's own minimal implementation of the PSR-3 Logger that is configured to `\Psr\Log\LogLevel::INFO`. If a different log level is desired, we advise that you use a more fully featured 3rd party logger that also implements the PSR-3 interface. The logger instance can be passed as the 2nd argument when creating an instance of the `Client`.
Setting level `DEBUG` will log headers, request, and response bodies. This will produce a significant amount of logs of potentially sensitive information. The `DEBUG` level should not be used outside of a testing environment.
```shell
[2020-09-15T17:06:42+0000] Recurly.info: Request {"method":"POST","path":"\/accounts"} …
```

Adding \Recurly\Logger class and the ability to configure a logger

---

Tests/Recurly/Account_List_Test.php
Tests/Recurly/Invoice_List_Test.php
Tests/Recurly/ShippingAddress_Test.php
Tests/fixtures/accounts/index-200-take.xml
Tests/fixtures/invoices/index-200-take.xml
Tests/fixtures/shipping_addresses/index-200-take.xml
lib/recurly/account_list.php
lib/recurly/coupon_list.php
lib/recurly/invoice_list.php
lib/recurly/item_list.php
lib/recurly/pager.php
lib/recurly/plan_list.php
lib/recurly/shipping_address_list.php
lib/recurly/subscription_list.php
lib/recurly/transaction_list.php
lib/recurly/usage_list.php

```php
$params = [
"order" => "desc",
];
$accounts = Recurly_AccountList::take(2, $params);
```

Implement Pager#take

---

lib/recurly/addon.php

Because `item_state` and `external_sku` are included in the xml response for item-based add-ons, it would be good practice to expose this fields to the programmer.

Add item_state and external_sku to phpdocs

---

lib/recurly/client.php
lib/recurly/resources/subscription.php
openapi/api.yaml

- Adds the `state` parameter to the `listAccountCouponRedemptions` operation.
- Adds the `charge` parameter to the `terminateSubscription` operation so that a merchant can choose to not bill a customer for un-billed usage when terminating a subscription

Latest Changes for 2019-10-10

---

CHANGELOG.md

Stop living in the past. It's 2021.

Correct changelog year from 2020 to 2021

---

.bumpversion.cfg
composer.json
lib/recurly/version.php

[Full Changelog](https://github.com/recurly/recurly-client-php/compare/3.11.0...HEAD)
The 4.x major version of the client pairs with the `v2021-02-25` API version. This version of the client and the API contain breaking changes that should be considered before upgrading your integration.
All changes to the core API are documented in the [Developer Portal changelog](https://developers.recurly.com/api/changelog.html#v2021-02-25---current-ga-version)
- Require query string parameters to be specified under the `params` key of the `$options` parameter. [[#522](https://github.com/recurly/recurly-client-php/pull/522)]
```php
$options = [
'limit' => 200
];
$accounts = $client->listAccounts($options);
```
```php
$options = [
'params' => [
'limit' => 200
],
'headers' => [
'Accept-Language' => 'fr' …
```

Release 4.0.0

---

lib/recurly/recurly_resource.php
tests/RecurlyResource_Test.php

Addresses report where a subscription/plan with `unitAmount` of zero will return `NULL` when calling `getUnitAmount()`, when desired result is to return a float type of zero. `empty()` was [too inclusive](https://www.w3schools.com/php/func_var_empty.asp).

Replace empty() with is_null()

---

.travis.yml
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
composer.json
lib/recurly/base_client.php
lib/recurly/http_adapter.php
lib/recurly/logger.php
lib/recurly/page.php
lib/recurly/pager.php
lib/recurly/recurly_resource.php
lib/recurly/request.php
lib/recurly/response.php
phpunit.xml.dist
scripts/clean
tests/BaseClient_Test.php
tests/Logger_Test.php
tests/Page_Test.php
tests/Pager_Test.php
tests/RecurlyError_Test.php
tests/RecurlyResource_Test.php
tests/Request_Test.php
tests/Response_Test.php
tests/bootstrap.php
tests/mock_client.php
tests/recurly/resources/test_resource.php

Some updates added to the 3.x client were missed when creating the 4.x client.

Sync updates not ported from 3.x client

---

.github_changelog_generator
composer.json

Internal only update to ignore issues and pull requests with the `internal` label from changelog generation.

Ignoring 'internal' tags in changelog generation
